### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by fenglui** [harry0703/MoneyPrinterTurbo#1]
```shell
git clone https://github.com/harry0703/MoneyPrinterTurbo.git
cd MoneyPrinterTurbo
conda create -n mpt python=3.10
conda activate mpt
pip install -r requirements.txt
cp config.example.toml config.toml
# 配置 `config.toml` 中的参数后
sh webui.sh
```

 *****Current directory: /mnt/e/ML/llm-pro/MoneyPrinterTurbo

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.2.2:8501

2024-03-11 23:39:15.635 Uncaught app exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/mpt/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/mnt/e/ML/llm-pro/MoneyPrinterTurbo/webui/Main.py", line 6, in <module>
    from app.models.schema import VideoParams, VideoAspect, VoiceNames
ModuleNotFoundError: No module named 'app'

**Comment by fenglui** [comment]
I fixed this by change
export PYTHONPATH="${CURRENT_DIR}:$PYTHONPATH"
to
export PYTHONPATH="${CURRENT_DIR}:/root/miniconda3/envs/mpt"

and then I met a huggingface_hub connection error

then I add the env

export HF_ENDPOINT=https://hf-mirror.com

then I saw the model download in progress

**Comment by xiemuyou** [comment]
![error](https://github.com/harry0703/MoneyPrinterTurbo/assets/12929443/7dd76a38-4e93-45de-b1ba-31ad9b62abab)
我也同样的错误, 修改了PYTHONPATH错误依然存在

**Comment by harry0703** [comment]
```
export PYTHONPATH="你的项目的绝对路径，就是你截图中的 D盘路径"
```
试试看

**Comment by TheDevelolper** [comment]
I'm using this inside of a dev container so I have control of where the python installation etc is.

I ran `which python` and it gave me `/usr/local/bin/python`

so I changed my webui.sh like this: 

``` bash
CURRENT_DIR="/workspaces/MoneyPrinterTurbo"
echo "***** Current directory: $CURRENT_DIR *****"
export PYTHONPATH="${CURRENT_DIR}:/usr/local/bin"
streamlit run ./webui/Main.py
```

however I still get the error: 

```
ModuleNotFoundError: No module named 'app'
Traceback:
File "/home/vscode/.local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "/workspaces/MoneyPrinterTurbo/webui/Main.py", line 24, in <module>
    from app.models.schema import VideoParams, VideoAspect, VideoConcatMode
```
