### ISSUE TITLE
为什么视频内容和咒语内容大相径庭？

### ISSUE THREAD

**Issue by jiangaq** [harry0703/MoneyPrinterTurbo#103]

**Comment by harry0703** [comment]
目前对一些 **复杂 的视频主题**，视频内容的匹配度会稍差一点，这个在优化中。
后续版本会改善

**Comment by suxici** [comment]
我感觉是从prompt中抽取关键字，然后找相关视频拼接起来，不是生成的视频，跟大模型没什么关系

**Comment by jiangaq** [comment]
好像是的，LLM生成关键字，然后到pexels下载视频，再拼起来的
可好像pexels用关键字找的视频有问题
应该每句台词所对应的视频，能对的上当前台词中的关键字才合理吧

**Comment by 907080752** [comment]
拼接的....

**Comment by Doubiiu** [comment]
属于是抖机灵的“AI视频生成”

**Comment by harry0703** [comment]
@jiangaq 
> 应该每句台词所对应的视频，能对的上当前台词中的关键字才合理吧

目前正在优化视频的匹配度
