### ISSUE TITLE
APITimeoutError: Request timed out.这个错误是因为网络不好吗？能不能不经过chatgpt处理，应该在哪里设置呢？请教！

### ISSUE THREAD

**Issue by cheng0009** [harry0703/MoneyPrinterTurbo#104]
APITimeoutError: Request timed out.
Traceback:
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py”, line 542, in _run_script
exec(code, module.dict)
File “E:\MoneyPrinterTurbo-main\webui\Main.py”, line 154, in <module>
tm.start(task_id=task_id, params=cfg)
File “E:\MoneyPrinterTurbo-main\app\services\task.py”, line 46, in start
script = llm.generate_script(video_subject=video_subject, language=language, paragraph_number=paragraph_number)
File “E:\MoneyPrinterTurbo-main\app\services\llm.py”, line 93, in generate_script
response = _generate_response(prompt=prompt)
File “E:\MoneyPrinterTurbo-main\app\services\llm.py”, line 55, in _generate_response
response = client.chat.completions.create(
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai_utils_utils.py”, line 275, in wrapper
return func(*args, **kwargs)
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai\resources\chat\completions.py”, line 667, in create
return self._post(
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai_base_client.py”, line 1208, in post
return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai_base_client.py”, line 897, in request
return self._request(
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai_base_client.py”, line 935, in _request
return self._retry_request(
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai_base_client.py”, line 1021, in _retry_request
return self._request(
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai_base_client.py”, line 935, in _request
return self._retry_request(
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai_base_client.py”, line 1021, in _retry_request
return self._request(
File “G:\Aconda3\envs\MoneyPrinterTurbo\lib\site-packages\openai_base_client.py”, line 945, in _request
raise APITimeoutError(request=request) from err

**Comment by harry0703** [comment]
这个是网络问题，如果无法访问openai
可以使用 `moonshot（月之暗面）`，`qianwen（通义千问）` 等国内模型

**Comment by ttt-y** [comment]
同样的问题，请问您是怎么解决的？
