### ISSUE TITLE
APITimeoutError: Request timed out

### ISSUE THREAD

**Issue by gaoxinghua951** [harry0703/MoneyPrinterTurbo#108]
请问是我配置有问题吗？我这边可以科学上网的
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/84117658/36f11c79-5fdc-497a-9e0f-3d02a4bd2857)
openai的密钥也是设置了的
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/84117658/b3a7d8ca-05fa-4408-9362-4d5304f94e1b)

**Comment by gaoxinghua951** [comment]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/84117658/ae7a1424-b2db-40e4-b398-c68599b6e708)
配置了梯子的广播地址后还是报错

**Comment by smaltum** [comment]
@gaoxinghua951 
配置信息无误的话，梯子设置全局代理试试？

**Comment by gaoxinghua951** [comment]
> @gaoxinghua951 配置信息无误的话，梯子设置全局代理试试？

设置了全局也不行

**Comment by gaoxinghua951** [comment]
找到原因了，是配置文件的openai_model_name 设置错误了，设置成gpt-3.5-turbo-16k-0613后成功运行
