### ISSUE TITLE
如何设置代理？

### ISSUE THREAD

**Issue by osmboy** [harry0703/MoneyPrinterTurbo#11]
下载视频老是出错，可以添加http代理吗？
<img width="1914" alt="image" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/20849756/d93c596b-d8ef-4408-b247-a13d8daaadfa">

**Comment by fenglui** [comment]
@osmboy 修改 material.py，比如下面

@harry0703 是否可以加个配置项到config

···python
proxies={
    "http":"http://127.0.0.1:1082",
    "https":"http://127.0.0.1:1082",
}

def save_video(video_url: str, save_dir: str) -> str:
    video_id = f"vid-{str(int(time.time() * 1000))}"
    video_path = f"{save_dir}/{video_id}.mp4"
    with open(video_path, "wb") as f:
        f.write(requests.get(video_url, proxies=proxies).content)

    return video_path
···

**Comment by harry0703** [comment]
@fenglui 已增加配置项

```toml
[pexels]
    [pexels.proxies]
        ### Use a proxy to access the Pexels API
        ### Format: "http://<username>:<password>@<proxy>:<port>"
        ### Example: "http://user:pass@proxy:1234"
        ### Doc: https://requests.readthedocs.io/en/latest/user/advanced/#proxies
        # http = "http://10.10.1.10:3128"
        # https = "http://10.10.1.10:1080"
```
