### ISSUE TITLE
centos7在组合视频的时候报错了

### ISSUE THREAD

**Issue by jiadoudou03** [harry0703/MoneyPrinterTurbo#110]
查看issues里大家遇到的问题，尝试了修改 ulimit -n 10240,ulimit -l 4096 ，修改moviepy及pillow的版本都没有解决问题，辛苦给看看如何解决！！看报错是ffmpeg写文件的时候Broken pipe了，不清楚是否和ffmpeg版本有关，有否有最后合成时用到的ffmpeg命令可以debug模式在log打出来方便排查问题
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/149230600/5073afea-be42-4c0d-9b0a-9acf34c69a03)

**Comment by harry0703** [comment]
或者试试 将 imageio-ffmpeg 版本从 0.4.9 降级到 0.2.0 试试，我Google了一下
有用户遇到这个问题，降级后解决了

**Comment by jiadoudou03** [comment]
@harry0703  @smaltum 多谢回复， imageio-ffmpeg 降了版本仍然报这个错，感觉可能是配置低的问题，我再找台好点的机器试试，多谢了🙏

**Comment by jiadoudou03** [comment]
@smaltum 换了台4核16G的机器，可以正常生成了，多谢〜
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/149230600/16ccf0f2-a635-45c9-b58d-ad5ffefb73f6)
