### ISSUE TITLE
当前地区当日额度已消耗完, 请尝试更换网络环境

### ISSUE THREAD

**Issue by 907739769** [harry0703/MoneyPrinterTurbo#113]
当前地区当日额度已消耗完, 请尝试更换网络环境

**Comment by 907739769** [comment]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/27858369/a13ee744-84a2-477a-a6ac-2715c44d5f6d)

**Comment by smaltum** [comment]
@907739769 换个key试试

**Comment by harry0703** [comment]
G4F是一个免费的 gpt api 服务，稳定性不太好，加上用的人多，很可能被限流
建议使用 openai 的，或者使用 国内 的，更稳定一些
