### ISSUE TITLE
自定义文案，如果文字过多（200多个字），好像会导致语音过长报错

### ISSUE THREAD

**Issue by youngphp** [harry0703/MoneyPrinterTurbo#117]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/15190634/1a11133c-d579-4abc-a3c0-b492b3cc0517)

**Comment by harry0703** [comment]
可以把输出目录下面的 script.json 和 audio.mp3 打包上传到这里，我优化下
谢谢~

另外会有补偿机制，如果生成失败后，会用 `whisper` 继续生成字幕

**Comment by harry0703** [comment]
是否方便把该任务目录下面的  script.json 上传到这里，我定位下问题
谢谢~

**Comment by youngphp** [comment]
[script.zip](https://github.com/harry0703/MoneyPrinterTurbo/files/14813873/script.zip)
这个就是

**Comment by youngphp** [comment]
> 是否方便把该任务目录下面的 script.json 上传到这里，我定位下问题
> 谢谢~

已上传

**Comment by harry0703** [comment]
我这里测试是可以正常生成的
edge模式的字幕生成，有做过优化
建议你 `git pull` 更新下代码，然后再试试看
