### ISSUE TITLE
请问是否可以指定输出目录？

### ISSUE THREAD

**Issue by RuoYear** [harry0703/MoneyPrinterTurbo#118]
例如tasks里的数据
缓存数据可以指定保存在其它位置（例如windows的Temp里）
最终文件保存在另外位置（另外指定到最终目录，以日期作为文件夹命名）
文件名则是生成的具体时间
并且记录一个log代表生成时所用到的prompt和文件放一起

**Comment by smaltum** [comment]
@RuoYear 目前是以os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))为基准目录，可以在代码中调整下

**Comment by RuoYear** [comment]
谢谢，收到，或许后期可以加在配置文件里供人调整
