### ISSUE TITLE
How To Add A Language ?

### ISSUE THREAD

**Issue by alexdo83** [harry0703/MoneyPrinterTurbo#119]
I want to add a my local language, please guide me how to add it?

![webui-en](https://github.com/harry0703/MoneyPrinterTurbo/assets/25850343/c1f2bbe2-054c-46e5-97ed-8a41274e6643)

**Comment by harry0703** [comment]
webui/Main.py
1, line 207, add vi-VN
2, line 272, add vi-VN

**Comment by danicruz0415** [comment]
Hi, I was reading the code looking into this. I have not tested this so I am not sure if I am missing something but so far this is what I found:

### Add language support to the user interface
Add a new file inside `webui/i18n/` with the name of your language and all the translations inside. For example `jp.json`. I think the easiest way is to copy other language to have all the keys and translate

### Add language support to the voice generator
It seems  that voice is handled in the [MoneyPrinterTurbo/app/services/voice.py](https://github.com/harry0703/MoneyPrinterTurbo/blob/478207fa7b58af5a715235cded7f86eefefe3a78/app/services/voice.py) file. Voices are defined in the [get_all_voices](https://github.com/harry0703/MoneyPrinterTurbo/blob/478207fa7b58af5a715235cded7f86eefefe3a78/app/services/voice.py#L14) method. I think you can add the appropiate voice for your language there.

As far as I could see, the voices are loaded directly from Azure text to speech service when calling the `tts` function. So to check the available voices you can head on to the [language-support list](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts) and use the one appropiate for your language

Also the list of available voices is on the documentation under the [docs/voice-list.txt](https://github.com/harry0703/MoneyPrinterTurbo/blob/478207fa7b58af5a715235cded7f86eefefe3a78/docs/voice-list.txt) file so it would be good to update that as well

The list of voices seems to be on the [MoneyPrinterTurbo/app/models/schema.py](https://github.com/harry0703/MoneyPrinterTurbo/blob/478207fa7b58af5a715235cded7f86eefefe3a78/app/models/schema.py#L37) file as well, but its commented out, so I think this is not necessary to update

This is all I found. Sorry I missed something but I think this should work. Maybe @harry0703 could tell if I missed something or if there is any mistake.
