### ISSUE TITLE
去pexels查询视频都是0，导致无视频可以下载

### ISSUE THREAD

**Issue by justone25** [harry0703/MoneyPrinterTurbo#120]
<img width="1504" alt="image" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/13493912/3a19086c-37f6-4f8f-a260-e67f385e6139">

**Comment by harry0703** [comment]
可以先输入视频主题，然后用AI先生成 文案 和 关键词
如果关键词为非英文，需要手动调为`英文`
或者再次执行，直到生成英文为止

因为AI大模型，有时候不一定遵循指令
如果你用的是**OPENAI GPT4**，会**更稳定**一些
