### ISSUE TITLE
web continue runing

### ISSUE THREAD

**Issue by ximu-li** [harry0703/MoneyPrinterTurbo#121]
![screenshot-1711801680200](https://github.com/harry0703/MoneyPrinterTurbo/assets/125632075/bc364d9a-ce97-4ad8-8822-383f57ed626c)
***** Current directory: D:\moneyprinterturbo\MoneyPrinterTurbo *****

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.0.0.155:8501

2024-03-30 20:25:04.796 | INFO     | app.config.config:<module>:15 - load config from file: D:\moneyprinterturbo\MoneyPrinterTurbo/config.toml
无报错 但是web一直在running  请大佬指导一下

**Comment by ximu-li** [comment]
已经解决

**Comment by harry0703** [comment]
请问是什么原因？方便分享一下么，其他用户可能也会遇到这个问题 :)

**Comment by ximu-li** [comment]
imagemagick_path   路径错误 我重新修改了路径 正常run
