### ISSUE TITLE
中英文两个系统可以做成一个系统

### ISSUE THREAD

**Issue by LiuXianJing** [harry0703/MoneyPrinterTurbo#124]
目前我了解到有中文和英文两个对应的系统，其实可以做成一个系统的，做国际化处理（多语言处理）。这样如果要拓展其它更多国家语言，就不用部署很多网站了

**Comment by harry0703** [comment]
感谢建议
你是指哪个系统（或网站）？

**Comment by LiuXianJing** [comment]
这个系统：
中文版：https://reccloud.cn/
英文版：https://reccloud.com/

**Comment by harry0703** [comment]
感谢反馈，这个是项目赞助方的网站
中文版：https://reccloud.cn/ 【这个是面向国内用户的】
英文版：https://reccloud.com/【这个是面向海外用户的】

2个网站`部署的区域`不一样，有法律法规的要求😀

**Comment by LiuXianJing** [comment]
OK, 明白了

**Comment by JannyMon** [comment]
> 这个系统： 中文版：https://reccloud.cn/ 英文版：https://reccloud.com/
仔细看了生成的视频，根本不是AI大模型创作出来的，把别人网上的数据爬下来合成出来的，打着AI大模型的旗号搞得，真是见鬼了，本质核心都是从这里获取视频：https://www.pexels.com/，前面套了个大模型的壳子进行标签和语义理解，然后去免费的视频网站搜索对应标签的视频，在下载合成，和别人真正的sora创作生成视频完全不是一回事。

**Comment by harry0703** [comment]
@JannyMon 是的，是通过AI生成视频文案和关键词，然后匹配对应的素材，使用 moviepy合成的。
不是sora那种
2种方式，都有受众人群和场景
