### ISSUE TITLE
openapi请求频率过高

### ISSUE THREAD

**Issue by Dethic** [harry0703/MoneyPrinterTurbo#125]
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

使用的是免费的gpt3.5-turbo，看openapi的解释时请求频率过高，没看到issue反馈这个问题，都是怎么解决这个问题的呢？

**Comment by harry0703** [comment]
你可以申请提高额度
或者用国内的大模型

在 2024年3月31日，09:44，Dethic ***@***.***> 写道：

﻿

openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

使用的是免费的gpt3.5-turbo，看openapi的解释时请求频率过高，没看到issue反馈这个问题，都是怎么解决这个问题的呢？
