### ISSUE TITLE
Length video short

### ISSUE THREAD

**Issue by pupheng** [harry0703/MoneyPrinterTurbo#129]
after generate video succeed length of video and prompt not match video generate seem too short after final combined together. do you have any suggestion ?

**Comment by harry0703** [comment]
The length of the video depends on the length of the video script. I suggest you first use AI to generate a video script and keywords. If the video script is too short, you can manually adjust it or use AI to generate it several times until you are satisfied with the length of the script before proceeding to create the video. This might yield better results, and you can give it a try.

Additionally, I will also add more control parameters, such as options for the video length: short, medium, long, etc., for you to choose from.
