### ISSUE TITLE
无效生成视频

### ISSUE THREAD

**Issue by czqasngit** [harry0703/MoneyPrinterTurbo#13]
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

请问这个是需要在open.ai上面充值吗

**Comment by Illusionist0** [comment]
你的API应该是过期了，新号的API一般有时间限制和数量限制

**Comment by harry0703** [comment]
或者你换成 moonshot 模型，注册就送15块钱，测试用足够了
或者使用 g4f，免费的 gpt，但是4.0估计用不了，可以用3.5
