### ISSUE TITLE
Windows一键启动包(Portable Windows)

### ISSUE THREAD

**Issue by haoqiangyu** [harry0703/MoneyPrinterTurbo#132]
夸克网盘：
    链接：https://pan.quark.cn/s/95b261d6c89a
    提取码：QRjp
md5: a79caf91fc261049373f816fb6b40be5

**Comment by SingingDalong** [comment]
Thank you.

**Comment by SingingDalong** [comment]
However, the download speed is less than 50kb. I would appreciate it if you could share it with Baidu NetDisk and xunlei.

**Comment by haoqiangyu** [comment]
百度网盘分享的文件：https://pan.baidu.com/s/1ESyW6ep722tD1PrkAhXPiA?pwd=5ys5 
提取码:5ys5

**Comment by SingingDalong** [comment]
> 百度网盘：[https://pan.baidu.com/s/1ESyW6ep722tD1PrkAhXPiA?pwd=5ys5 ](https://pan.baidu.com/s/1ESyW6ep722tD1PrkAhXPiA?pwd=5ys5%C2%A0) 提取码:5ys5

哥哥。谢谢。

**Comment by qiangqianfei** [comment]
使用Windows一键启动包  ，填写了 Pexels API Key  报错，  麻烦您帮忙看看哪里不对。翻墙，不翻墙都已试过，还是报错。
![1](https://github.com/harry0703/MoneyPrinterTurbo/assets/165628894/932f2820-a60d-443b-b666-2487b52d7845)
![2](https://github.com/harry0703/MoneyPrinterTurbo/assets/165628894/ed05c1e6-e706-457d-9b9b-8275c0e82071)

**Comment by haoqiangyu** [comment]
> 使用Windows一键启动包  ，填写了 Pexels API Key  报错，  麻烦您帮忙看看哪里不对。翻墙，不翻墙都已试过，还是报错。
> ![1](https://github.com/harry0703/MoneyPrinterTurbo/assets/165628894/932f2820-a60d-443b-b666-2487b52d7845)
> ![2](https://github.com/harry0703/MoneyPrinterTurbo/assets/165628894/ed05c1e6-e706-457d-9b9b-8275c0e82071)
> 

少了个方括号

**Comment by SingingDalong** [comment]
You will also need the moonshot API. However, the moonshot API requires a Chinese phone. So I couldn't use it.

**Comment by SingingDalong** [comment]
> > 使用Windows一键启动包  ，填写了 Pexels API Key  报错，  麻烦您帮忙看看哪里不对。翻墙，不翻墙都已试过，还是报错。
> > ![1](https://private-user-images.githubusercontent.com/165628894/318339991-932f2820-a60d-443b-b666-2487b52d7845.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDg2OTMsIm5iZiI6MTcxMTk0ODM5MywicGF0aCI6Ii8xNjU2Mjg4OTQvMzE4MzM5OTkxLTkzMmYyODIwLWE2MGQtNDQzYi1iNjY2LTI0ODdiNTJkNzg0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwNTEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGViZmI5OWMzOTAwNjExZDcyZDE4NWQwNjI1YmRkODBiNjdkMGNlNzJjOWFhNmEzNGM2YmU1MjE5YzAyODYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wMNslv9sBRiSbSAAjhqhLFIMtUKYX4vKLXVJNI_bipA)
> > ![2](https://private-user-images.githubusercontent.com/165628894/318339997-ed05c1e6-e706-457d-9b9b-8275c0e82071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDg2OTMsIm5iZiI6MTcxMTk0ODM5MywicGF0aCI6Ii8xNjU2Mjg4OTQvMzE4MzM5OTk3LWVkMDVjMWU2LWU3MDYtNDU3ZC05YjliLTgyNzVjMGU4MjA3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwNTEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGI0OTU3YmM4YmY1NjEyM2U2YmQ0MWFkMmJiNGEwZTQzMDdhOWRmNmUyOTc3YjgxMmJmYTBmNmE0NWE0YTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vnVTQPG23KM0qlAaXr8vzT_u0jt4C8mobTT-CK_T_LM)
> 
> 少了个方括号

You will also need the moonshot API. However, the moonshot API requires a Chinese phone. So I couldn't use it.

**Comment by haoqiangyu** [comment]
@SingingDalong You can use llm on different platforms by modifying `llm_provider` and filling in the corresponding API key.
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/38414214/8a6d38cb-5727-48ef-8f54-0fe9646df500)

**Comment by qiangqianfei** [comment]
多谢多谢，谢谢各位大哥

**Comment by yapthatsme** [comment]
你们中有人能上传到另一个镜像吗？如果不住在中国，从百度和夸克下载并不容易。非常感谢.

Could any of you upload to another mirror? Downloading from Baidu and quark is not easy if you don't live in China. Thanks a lot.

**Comment by SingingDalong** [comment]
> 你们中有人能上传到另一个镜像吗？如果不住在中国，从百度和夸克下载并不容易。非常感谢.
> 
> Could any of you upload to another mirror? Downloading from Baidu and quark is not easy if you don't live in China. Thanks a lot.

https://mypikpak.com/s/VNuORojM1v2zGSOFwGA9TO7Ko1

You can sign up for PikPak ​​with your email(or Google account). For reference, PikPak ​​is used for torrent downloading. Please use Google search for more details.

**Comment by haoqiangyu** [comment]
Google Drive: https://drive.google.com/file/d/1FWUHRLrRFh1HmiMJl_3cLjjibt0hA9AL/view?usp=sharing 
@yapthatsme

**Comment by yapthatsme** [comment]
For PikPak I also needed a VPN at first because my region is not supported.  But it was much more relaxed because I didn't need a chinese phone number. At the end i used Google Drive because my VPN was really slow. Thank you very much, both of you.

**Comment by alistaitsacle** [comment]
可以使用这个地址测试：
http://ai.appleecg.com:8501/

**Comment by 1060404996** [comment]
为啥我打开第一步就不行，这是怎么会是，电脑配置太低了吗
![微信截图_20240409114722](https://github.com/harry0703/MoneyPrinterTurbo/assets/94887618/e073097a-22e5-48b2-811b-e0886d4495b9)

**Comment by yclwk** [comment]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/38937128/e7c16fb7-d427-498a-8b3f-a17ae76112d5)

**Comment by haoqiangyu** [comment]
@yclwk 
应该是权限问题
参考 https://blog.csdn.net/shaylo/article/details/125719378

**Comment by yclwk** [comment]
好 谢谢，我只设置了安全那块的权限。一会用管理员打开压缩软件再解压试试

| |
李文凯
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月09日 下午6:40 |
| 收件人 | harry0703/MoneyPrinterTurbo ***@***.***> |
| 抄送人 | liwenkai ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [harry0703/MoneyPrinterTurbo] Windows一键启动包(Portable Windows) (Issue #132) |

@yclwk
应该是权限问题
参考 https://blog.csdn.net/shaylo/article/details/125719378
