### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by ShaunTheCode** [harry0703/MoneyPrinterTurbo#133]
TypeError: cannot unpack non-iterable NoneType object
Traceback:
File "E:\devApps\Anaconda\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "E:\Code\MoneyPrinterTurbo\webui\Main.py", line 376, in <module>
    tm.start(task_id=task_id, params=params)
File "E:\Code\MoneyPrinterTurbo\app\services\task.py", line 138, in start
    video.generate_video(video_path=combined_video_path,
File "E:\Code\MoneyPrinterTurbo\app\services\video.py", line 214, in generate_video
    sub = SubtitlesClip(subtitles=subtitle_path, make_textclip=generator, encoding='utf-8')
File "E:\devApps\Anaconda\envs\MoneyPrinterTurbo\lib\site-packages\moviepy\video\tools\subtitles.py", line 69, in __init__
    self.duration = max([tb for ((ta, tb), txt) in self.subtitles])
File "E:\devApps\Anaconda\envs\MoneyPrinterTurbo\lib\site-packages\moviepy\video\tools\subtitles.py", line 69, in <listcomp>
    self.duration = max([tb for ((ta, tb), txt) in self.subtitles])

**Comment by harry0703** [comment]
Can you compress the files for this task and upload them here? 
This would make it easier for me to locate and troubleshoot the issue. 
Thank you.

**Comment by pupheng** [comment]
i have faced the same error when generate video.

**Comment by harry0703** [comment]
Thank you for your feedback.
Please compress the task forder, for example: `./storage/tasks/0fb89ebb-890f-4350-ba6a-bd9f4d18e362` and upload it here.
I will fix this bug.

**Comment by pupheng** [comment]
here is my error task in attachment, i have noticed that error come from video script long and generate with many scene cut. example i want to generate video tip for chose the right food for healthy, so many scene of each tip.

**Comment by pupheng** [comment]
file of task is too big, can not upload here. may i upload into google drive and drop link here? or you have any suggestion ?

**Comment by harry0703** [comment]
@pupheng ok, you can upload to Google drive, and post link here, thanks.

**Comment by pupheng** [comment]
@harry0703 please check the link below for error task generate:

https://drive.google.com/file/d/13kZ4sNYPOP6Uzqq3GrL57LIUnKnSUgX_/view?usp=sharing

**Comment by harry0703** [comment]
It has been fixed. 
You can try again after updating the code. 
If there are any issues, feel free to provide feedback.

**Comment by harry0703** [comment]
@pupheng 
It has been fixed.
You can try again after updating the code.
If there are any issues, feel free to provide feedback.
