### ISSUE TITLE
API接口如何后台合成视频，获取合成进度

### ISSUE THREAD

**Issue by qq1574829575** [harry0703/MoneyPrinterTurbo#140]
目前调用API接口生成视频，貌似是一个阻塞进程，我想实现调用后立即返回task_id，让视频后台生成。
或者调用api/v1/tasks接口能够实时获取到进度，有没有大致的思路呢？我想自己实现，但是py不太熟练，作者哥哥还有各位大佬能否指点一二，感激不尽

**Comment by KevinZhang19870314** [comment]
1. 后台进程可以使用fastapi的[BackgroundTasks](https://fastapi.tiangolo.com/tutorial/background-tasks/);
2. 另外一个查询状态接口作者好像还没有来得及实现，不过我觉得可以直接查询最终生成的视频是否存在，然后显示log实现查询状态。

**Comment by qq1574829575** [comment]
> 1. 后台进程可以使用fastapi的[BackgroundTasks](https://fastapi.tiangolo.com/tutorial/background-tasks/);
> 2. 另外一个查询状态接口作者好像还没有来得及实现，不过我觉得可以直接查询最终生成的视频是否存在，然后显示log实现查询状态。

感谢指点，我试试

**Comment by harry0703** [comment]
已经完成了该接口，可以更新代码
示例
```shell
curl --location 'http://127.0.0.1:8080/api/v1/tasks/e34b6124-7c53-4ee6-8d82-7f26a97451c3'
```
 返回

合成中：
```json
{
    "status": 200,
    "message": "success",
    "data": {
        "state": 4,
        "progress": 20
    }
}
```

合成完成：
```json
{
    "status": 200,
    "message": "success",
    "data": {
        "state": 1,
        "progress": 100,
        "videos": [
            "http://127.0.0.1:8080/tasks/6c85c8cc-a77a-42b9-bc30-947815aa0558/final-1.mp4"
        ]
    }
}
```
