### ISSUE TITLE
使用edge字幕生成失败

### ISSUE THREAD

**Issue by qcoltma** [harry0703/MoneyPrinterTurbo#144]
配置大模型为openai后，运行发现edge生成字幕失败，但是之前我配置模型为gemini时是可以用的，请问区别在哪里？怎么解决？

## generating subtitle, provider: edge
2024-04-02 10:05:51 | WARNING | "./app/services/voice.py:1089": create_subtitle - failed, sub_items len: 0, script_lines len: 11

**Comment by harry0703** [comment]
可以把任务目录下面的 script.json 上传到这里，我定位下问题，谢谢

**Comment by qcoltma** [comment]
[script.json](https://github.com/harry0703/MoneyPrinterTurbo/files/14832078/script.json)
已上传，谢谢

**Comment by harry0703** [comment]
测试了一下，我这里生成是正常的，请问您是使用的最新代码么？
可以 git pull 一下试试
