### ISSUE TITLE
生成final-1.mp4时闪退

### ISSUE THREAD

**Issue by troublemakerMibu** [harry0703/MoneyPrinterTurbo#145]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/121711734/4154d9fc-cb32-43ad-9b79-398ed782fd9f)
这是cmd界面输出的信息，之后就进程突然结束
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/121711734/51cbccf5-e833-4a87-bf31-6fbf9743e8d0)
这是webui界面输出的信息

**Comment by harry0703** [comment]
电脑配置是不是过低？CPU 4核或以上

**Comment by troublemakerMibu** [comment]
不排除这个可能。但是我在使用之前的版本的时候可以顺利生成final-1.mp4。是最近这次更新后才出现闪退的情况。

**Comment by qikh** [comment]
同样的问题，win11，cpu Intel 11800，gpu rtx3070，性能应该足够了，但是每次到final-1.mp4.temp.mp4，webui控制台就会退出。

**Comment by HeathKang** [comment]
试试把write_videofile的progress bar关掉，这个貌似会很占IO
 ```
final_clip.write_videofile(combined_video_path, threads=threads, logger=None)
```
[Zulko/moviepy#645](https://github.com/Zulko/moviepy/issues/645)

**Comment by troublemakerMibu** [comment]
我在去掉勾选“启用字幕”选项后可以顺利生成final-1.mp4

**Comment by troublemakerMibu** [comment]
更新了代码之后，使用logger=None的方法但是闪退依然出现，不启用字幕则正常，推测和字幕合成有关

**Comment by harry0703** [comment]
@troublemakerMibu  这个还要定位一下，你也是Windows吧？好像都是Windows反馈这个问题
