### ISSUE TITLE
为什么不使用“gpt4free”模型？

### ISSUE THREAD

**Issue by alexdo83** [harry0703/MoneyPrinterTurbo#15]
为什么不使用“gpt4free”模型？

**Comment by harry0703** [comment]
感觉 gpt4free 稳定性不行，能用的概率太低了啊

**Comment by alexdo83** [comment]
> 感觉 gpt4free 稳定性不行，能用的概率太低了啊

但gpt4型号对很多人来说太贵了 :(

**Comment by alexdo83** [comment]
你能创建一个免费的 gpt4free 选项吗？

**Comment by harry0703** [comment]
可以的
也可以先用 Moonshot 的模型，我测试效果也还不错。注册就送1500次左右对话。
https://platform.moonshot.cn/console/api-keys

**Comment by harry0703** [comment]
@alexdo83 已增加 `g4f` 的支持
