### ISSUE TITLE
stretched videos in landscape mode

### ISSUE THREAD

**Issue by Kredithaichen** [harry0703/MoneyPrinterTurbo#150]
When generating videos in landscape mode, oftentimes one of the video snippets selected is actually in portrait mode and will be stretched to fit the new aspect ratio. The same snippet was correctly used in a portrait mode video, so I don't think it is just incorrectly labeled data from Pexels.

**Comment by harry0703** [comment]
This seems to have a bug, I will fix it as soon as possible.

**Comment by harry0703** [comment]
It has been fixed. 
You can try again after updating the code. 
If there are any issues, feel free to provide feedback.
