### ISSUE TITLE
Added stray frames

### ISSUE THREAD

**Issue by Kredithaichen** [harry0703/MoneyPrinterTurbo#151]
Depending on the overall duration, the generated video has often a few frames of another snippet appended at the very end, creating a very jarring cutoff effect. Maybe there is a way to pad the video with an extra second or two if the concatenated snippets don't fit exactly the script length?

**Comment by harry0703** [comment]
This seems to have a bug, I will fix it as soon as possible.
Could you please upload the final video (final.mp4), and the video script (script.json) here for review? 
Thank you.
