### ISSUE TITLE
Bad cropping of video snippets

### ISSUE THREAD

**Issue by Kredithaichen** [harry0703/MoneyPrinterTurbo#152]
In some cases snippets are cropped poorly and stretch to an incorrect aspect ratio. See the following for comparison: 

https://github.com/harry0703/MoneyPrinterTurbo/assets/31171070/b61b1439-707a-4fd8-9b0e-3f78fb3e2cbe

https://github.com/harry0703/MoneyPrinterTurbo/assets/31171070/38ccdc33-44e0-416b-9efd-49a70bdd2e1e

**Comment by harry0703** [comment]
Thank you for your feedback.
This seems to have a bug, I will fix it as soon as possible.

**Comment by harry0703** [comment]
Hi, I have fixed this issue, please update the code, and try again.
Thanks.
