### ISSUE TITLE
Connection error Is Streamlit still running? If you accidentally stopped Streamlit, just restart it in your terminal:  streamlit run yourscript.py

### ISSUE THREAD

**Issue by anetakahle** [harry0703/MoneyPrinterTurbo#155]
When I try to run webui.bat, it always crashes on this:
![Screenshot 2024-04-02 215215](https://github.com/harry0703/MoneyPrinterTurbo/assets/29632816/3209c01f-0b99-42af-a48d-cc84fe131b46)
![Screenshot 2024-04-02 215155](https://github.com/harry0703/MoneyPrinterTurbo/assets/29632816/34d98f2f-634b-4c23-ab2a-a9fbaf4d39e9)

When I run it with main.py (I dont know what else to run it with) it crashes with "ERROR:    [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8080): only one usage of each socket address (protocol/network address/port) is normally permitted"

**Comment by harry0703** [comment]
https://github.com/harry0703/MoneyPrinterTurbo/issues/111#issuecomment-2032354030

Let's try this solution to see if it works properly.

**Comment by harry0703** [comment]
It has been fixed. 
You can try again after updating the code. 
If there are any issues, feel free to provide feedback.
