### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by javatomatos** [harry0703/MoneyPrinterTurbo#16]
config.toml配置文件修改为llm_provider="moonshot"，我也设置了moonshot的api key，但在生成视频的时候出现
openai.APIConnectionError: Connection error.

**Comment by harry0703** [comment]
moonshot也不需要翻墙，是可以直接连接的。
你可以上github，说明是开了VPN，关掉VPN试试呢？

**Comment by hy546880109** [comment]
> moonshot也不需要翻墙，是可以直接连接的。 你可以上github，说明是开了VPN，关掉VPN试试呢？

关闭VPN。提示 failed to download videos, maybe the network is not available. if you are in China, please use a VPN.
打开VPN，提示 openai.APIConnectionError: Connection error.  那么需要怎样才能解决呢
