### ISSUE TITLE
User location is not supported for the API use

### ISSUE THREAD

**Issue by jeffreyrobeson** [harry0703/MoneyPrinterTurbo#160]
llm_provider="gemini"
google.api_core.exceptions.BadRequest: 400 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: User location is not supported for the API use.

**Comment by harry0703** [comment]
You may need to use a VPN as Gemini has country restrictions and is not available in some countries.

**Comment by jeffreyrobeson** [comment]
如何修改反代理？
