### ISSUE TITLE
作者你好，请问生成视频的时候如下报错是怎么回事，OpenAI API Key、Pexels API Key都正常

### ISSUE THREAD

**Issue by cfy3133** [harry0703/MoneyPrinterTurbo#162]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/43978367/0953d3f7-204b-4de4-9475-2b1512063707)

**Comment by harry0703** [comment]
因为你的 OpenAI API Key 没有访问 gpt-4-turbo-preview 的权限
到这里查看 https://platform.openai.com/account/limits
选择被授权的模型
