### ISSUE TITLE
APIConnectionError

### ISSUE THREAD

**Issue by gaoxinghua951** [harry0703/MoneyPrinterTurbo#165]
前几天可以正常运行，今天再次运行报错如下：
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/84117658/bfe49db2-a565-4842-a89a-b9c178da20c4)
我重新更换openai_api_key和openai_base_url后仍然报相同错误，期待作者解答

**Comment by gaoxinghua951** [comment]
我这边梯子和gpt都是可以正常使用的，代理也设置的是全局代理

**Comment by karlca** [comment]
我第一次运行，都是报这个错误，网络也是正常的

**Comment by gaoxinghua951** [comment]
> 我第一次运行，都是报这个错误，网络也是正常的
我之前是成功运行了的，后面也没改配置，再运行就是这个错误了，现在在研究怎么g4f的key，您有研究嘛

**Comment by harry0703** [comment]
@karlca 你用国内的模型看看，月之暗面 moonshot，应该可以直接访问。openai需要全局VPN，并且还有国家和地区限制

**Comment by gaoxinghua951** [comment]
> 我第一次运行，都是报这个错误，网络也是正常的

我第一次运行，都是报这个错误，网络也是正常的
我之前是成功运行了的，后面也没改配置，再运行就是这个错误了，现在在研究怎么g4f的key，您有研究嘛

**Comment by gaoxinghua951** [comment]
> 你用国内的模型看看，月之暗面 大胆创新计划，应该可以直接访问。openai需要全局VPN，并且还有国家和地区限制

我的vpn节点是日本和新加坡的

**Comment by harry0703** [comment]
@gaoxinghua951 g4f，你直接改 `llm_provider="g4f"` 即可，模型就用 `g4f_model_name = "gpt-3.5-turbo-16k-0613"`
但是毕竟是薅羊毛的，因此 g4f 的稳定性不太好，有时候可以用，有时候不能

**Comment by gaoxinghua951** [comment]
> @gaoxinghua951 g4f，你直接改 即可，模型就用 但是毕竟是薅羊毛的，因此 g4f 的稳定性不太好，有时候可以用，有时候不能`llm_provider="g4f"``g4f_model_name = "gpt-3.5-turbo-16k-0613"`

好的，谢谢作者，我试试

**Comment by harry0703** [comment]
[OpenAI宣布ChatGPT里面3.5已经免费了](https://openai.com/blog/start-using-chatgpt-instantly)，有开发者将其封装成了API，可以直接调用

**确保你安装和启动了docker服务**，执行以下命令启动docker服务
```shell
docker run -p 3040:3040 missuo/freegpt35
```
启动成功后，修改 `config.toml` 中的配置
- `llm_provider` 设置为 `openai`
- `openai_api_key` 随便填写一个即可，比如 '123456'
- `openai_base_url` 改为 `http://localhost:3040/v1/`
- `openai_model_name` 改为 `gpt-3.5-turbo`

**Comment by gaoxinghua951** [comment]
> [OpenAI宣布ChatGPT里面3.5已经免费了](https://openai.com/blog/start-using-chatgpt-instantly)，有开发者将其封装成了API，可以直接调用
> 
> **确保你安装和启动了docker服务**，执行以下命令启动docker服务
> 
> ```shell
> docker run -p 3040:3040 missuo/freegpt35
> ```
> 
> 启动成功后，修改 中的配置`config.toml`
> 
> * `llm_provider`设置为`openai`
> * `openai_api_key`随便填写一个即可，比如 '123456'
> * `openai_base_url`改为`http://localhost:3040/v1/`
> * `openai_model_name`改为`gpt-3.5-turbo`

收到，谢谢作者，
