### ISSUE TITLE
生成的时候huggingface_hub工具包提示下载失败

### ISSUE THREAD

**Issue by ayxworxfr** [harry0703/MoneyPrinterTurbo#166]
huggingface_hub.utils._errors.LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input

**Comment by TeachCourse** [comment]
默认有配置的环境变量，还是报错
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/17468835/7d3d2b97-c7ba-4253-8df8-8cbec31f7eb5)

**Comment by harry0703** [comment]
把注释去掉
rem
关键词移除掉
