### ISSUE TITLE
能否增加一个是否合成语音的选项

### ISSUE THREAD

**Issue by qq1574829575** [harry0703/MoneyPrinterTurbo#168]
增加一个选项是否朗读，选择不朗读则只合成视频，不合成语音
尝试了下自己实现，但是放弃了，目前来说超出了我的能力水平>.<

**Comment by qiqi258** [comment]
合成视频的文件夹里面就有无音频的视频。

> 增加一个选项是否朗读，选择不朗读则只合成视频，不合成语音 尝试了下自己实现，但是放弃了，目前来说超出了我的能力水平>.<

生成视频的文件里面就有无音频的视频文件。

**Comment by qq1574829575** [comment]
> 合成视频的文件夹里面就有无音频的视频。
> 
> > 增加一个选项是否朗读，选择不朗读则只合成视频，不合成语音 尝试了下自己实现，但是放弃了，目前来说超出了我的能力水平>.<
> 
> 生成视频的文件里面就有无音频的视频文件。

那个无音频是所有音频都没有，背景音乐也没有，我想的是，可以只合成背景音乐和视频

**Comment by harry0703** [comment]
挺好的想法，我加上去

**Comment by harry0703** [comment]
@qq1574829575 
发现不行，因为视频的长度，依赖音频的长度
如果不合成音频，就得`手动指定视频的长度`

**Comment by qq1574829575** [comment]
> @qq1574829575 发现不行，因为视频的长度，依赖音频的长度 如果不合成音频，就得`手动指定视频的长度`

哈哈没关系，其实我也发现了，所以我昨天提交了返回combined_videos的pr，让用户可以下载源视频，音频也好，配音也罢都让用户自己折腾
