### ISSUE TITLE
如果有GPU卡的，可以用ffmpeg的编码加速视频合成codec='h264_nvenc'

### ISSUE THREAD

**Issue by shanghailiwei** [harry0703/MoneyPrinterTurbo#171]
video.py:    final_clip.write_videofile(combined_video_path, codec='h264_nvenc', threads=threads, 
video.py:    result.write_videofile(temp_output_file, codec='h264_nvenc', threads=params.n_threads or 10,
video.py:    video_clip.write_videofile(output_file, codec='h264_nvenc', audio_codec="aac", threads=params.n_threads or 10,

**Comment by codehunterstories** [comment]
用的 moviepy 1.0.3 版本，默认使用的 ffmpeg 路径变成了：./site-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2，没有用到系统的 ffmpeg
然后一直提示找不到 h264_nvenc 编码格式。
需要手动配置一下路径才行：

from moviepy.config import change_settings, get_setting

change_settings({"FFMPEG_BINARY": "/path/to/your/ffmpeg"})

print(get_setting("FFMPEG_BINARY"))

**Comment by ck1123456** [comment]
> video.py: final_clip.write_videofile(combined_video_path, codec='h264_nvenc', threads=threads, video.py: result.write_videofile(temp_output_file, codec='h264_nvenc', threads=params.n_threads or 10, video.py: video_clip.write_videofile(output_file, codec='h264_nvenc', audio_codec="aac", threads=params.n_threads or 10,

您好，能否具体一点加到什么位置呢，是三个都加嘛，我在services中的video.py中只找到了video.py: final_clip.write_videofile(combined_video_path, codec='h264_nvenc', threads=threads, video.py: 和video_clip.write_videofile(output_file, codec='h264_nvenc', audio_codec="aac", threads=params.n_threads or 10,

**Comment by harry0703** [comment]
@ck1123456 就是 `video.py` 里面搜索  `write_videofile` ，修改即可

**Comment by ck1123456** [comment]
请问这个是不是在服务器上无法查到gpu使用呀，修改之后，在服务器上查询还是没有占用gpu

**Comment by harry0703** [comment]
看看ffmpeg的版本和编译信息
执行
```
ffmpeg
```
看看输出是否有 nvenc 的字样

**Comment by harry0703** [comment]
@ck1123456 示例

ffmpeg
ffmpeg version 2024-04-15-git-5e380bcdb1-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration:  --enable-libvpl **--enable-nvdec --enable-nvenc** --enable-vaapi
  libavutil      59. 15.100 / 59. 15.100
  libavcodec     61.  5.103 / 61.  5.103

**Comment by ck1123456** [comment]
请问ffmpeg怎么安装呢

**Comment by ck1123456** [comment]
您好我在linux输入ffmpeg有下面输出：
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc--enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by KeepMovingNo1** [comment]
webui    | 2025-02-18 15:32:07 | INFO | "./app/services/subtitle.py:26": create - loading model: ./models/whisper-large-v3, device: GPU, compute_type: int8_float16
webui    | 2025-02-18 15:32:07 | ERROR | "./app/services/subtitle.py:34": create - failed to load model: unsupported device GPU

**Comment by KeepMovingNo1** [comment]
nvidia-smi 
Tue Feb 18 23:33:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10                     On  |   00000000:00:06.0 Off |                    0 |
|  0%   32C    P8             16W /  150W |       4MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |

**Comment by KeepMovingNo1** [comment]
按照操作修改video.py 中几处及配置添加ffmpeg_path = "/usr/bin/ffmpeg"  均未使用GPU来渲染生成视频；请问还有可能问题出在哪儿？

配置文件：

![Image](https://github.com/user-attachments/assets/5ecca1b2-26d3-4f68-9837-ebf7d485cfe7)

video.py: 
![Image](https://github.com/user-attachments/assets/e5883b06-b312-448d-80d5-248472a2b6b1)

**Comment by kingproud** [comment]
1.确认你的GPU支持ffmpeg，MX系列显卡就不支持，可以问deepseek
2.下载ffmpeg，问deepseek要网址
3.修改config.toml，在[app]里面添加ffmpeg_path = "你的ffmpeg下载路径"
4.修改源码，找到app/services/video.py 修改3处write_videofile函数，在括号里面加入参数codec='h264_nvenc'
形如final_clip.write_videofile(combined_video_path, codec='h264_nvenc', threads=threads），记住有3个

**Comment by aibfarm** [comment]
> write_videofile

有４个write_videofile， 都改吗？

**Comment by harry0703** [comment]
@aibfarm 是的，相关的 write_videofile 都需要修改才行

**Comment by Zacharyii** [comment]
@KeepMovingNo1 我问题和你一样，你解决了吗？按照要求做了相应修改，但是不能使用GPU设备

![Image](https://github.com/user-attachments/assets/394dab97-93d2-4cda-a434-36bf0239199a)

**Comment by hkall** [comment]
当前在config.toml中按照注释，将CPU改为cuda，发现仍未调度gpu，整个过程也没报错，是还需要修改哪里吗？
