### ISSUE TITLE
第一次安装的时候没问题，第二次出现IsADirectoryError: [Errno 21] ，请问如何修复，谢谢。

### ISSUE THREAD

**Issue by tomisnotcat** [harry0703/MoneyPrinterTurbo#173]
api    | 2024-04-05 07:56:45.198 | INFO     | app.config.config:<module>:16 - load config from file: /MoneyPrinterTurbo/config.toml
api    | Traceback (most recent call last):
api    |   File "/MoneyPrinterTurbo/main.py", line 3, in <module>
api    |     from app.config import config
api    |   File "/MoneyPrinterTurbo/app/config/__init__.py", line 51, in <module>
api    |     __init_logger()
api    |   File "/MoneyPrinterTurbo/app/config/__init__.py", line 39, in __init_logger
api    |     logger.add(
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 795, in add
api    |     wrapped_sink = FileSink(path, **kwargs)
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 192, in __init__
api    |     self._create_file(path)
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 226, in _create_file
api    |     self._file = open(path, **self._kwargs)
api    | IsADirectoryError: [Errno 21] Is a directory: '/MoneyPrinterTurbo/storage/logs/server.log'
api exited with code 1

**Comment by codercoderme** [comment]
有同样的问题

**Comment by codercoderme** [comment]
api    | 2024-04-05 08:24:08.394 | INFO     | app.config.config:<module>:16 - load config from file: /MoneyPrinterTurbo/config.toml
api    | Traceback (most recent call last):
api    |   File "/MoneyPrinterTurbo/main.py", line 3, in <module>
api    |     from app.config import config
api    |   File "/MoneyPrinterTurbo/app/config/__init__.py", line 51, in <module>
api    |     __init_logger()
api    |   File "/MoneyPrinterTurbo/app/config/__init__.py", line 39, in __init_logger
api    |     logger.add(
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 795, in add
api    |     wrapped_sink = FileSink(path, **kwargs)
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 192, in __init__
api    |     self._create_file(path)
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 226, in _create_file
api    |     self._file = open(path, **self._kwargs)
api    | IsADirectoryError: [Errno 21] Is a directory: '/MoneyPrinterTurbo/storage/logs/server.log'

**Comment by harry0703** [comment]
更新代码试试

**Comment by codercoderme** [comment]
@harry0703  还是有同样的问题
 | 2024-04-07 10:58:35.397 | INFO     | app.config.config:<module>:16 - load config from file: /MoneyPrinterTurbo/config.toml
api    | Traceback (most recent call last):
api    |   File "/MoneyPrinterTurbo/main.py", line 3, in <module>
api    |     from app.config import config
api    |   File "/MoneyPrinterTurbo/app/config/__init__.py", line 51, in <module>
api    |     __init_logger()
api    |   File "/MoneyPrinterTurbo/app/config/__init__.py", line 39, in __init_logger
api    |     logger.add(
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 795, in add
api    |     wrapped_sink = FileSink(path, **kwargs)
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 192, in __init__
api    |     self._create_file(path)
api    |   File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 226, in _create_file
api    |     self._file = open(path, **self._kwargs)
api    | IsADirectoryError: [Errno 21] Is a directory: '/MoneyPrinterTurbo/storage/logs/server.log'

**Comment by harry0703** [comment]
更新代码，这个问题已经修复了

在 2024年4月7日，18:59，coderme ***@***.***> 写道：

﻿

@harry0703<https://github.com/harry0703> 还是有同样的问题
| 2024-04-07 10:58:35.397 | INFO | app.config.config::16 - load config from file: /MoneyPrinterTurbo/config.toml
api | Traceback (most recent call last):
api | File "/MoneyPrinterTurbo/main.py", line 3, in
api | from app.config import config
api | File "/MoneyPrinterTurbo/app/config/init.py", line 51, in
api | __init_logger()
api | File "/MoneyPrinterTurbo/app/config/init.py", line 39, in __init_logger
api | logger.add(
api | File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 795, in add
api | wrapped_sink = FileSink(path, **kwargs)
api | File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 192, in init
api | self._create_file(path)
api | File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 226, in _create_file
api | self._file = open(path, **self._kwargs)
api | IsADirectoryError: [Errno 21] Is a directory: '/MoneyPrinterTurbo/storage/logs/server.log'

**Comment by zonghua2016** [comment]
遇到同样的问题，求助
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/21120457/420075f1-f877-4678-ae71-ef09c8e50286)

**Comment by zonghua2016** [comment]
> 遇到同样的问题，求助 ![image](https://private-user-images.githubusercontent.com/21120457/321243055-420075f1-f877-4678-ae71-ef09c8e50286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTM2OTMsIm5iZiI6MTcxMjc1MzM5MywicGF0aCI6Ii8yMTEyMDQ1Ny8zMjEyNDMwNTUtNDIwMDc1ZjEtZjg3Ny00Njc4LWFlNzEtZWYwOWM4ZTUwMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEyNDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZGE3MWRjNDcxM2U5YWJmMmRmNThlZTQxODNiMzhmNjE5ZGZjMmNlMTllNjZhNGM5MDM4M2ZhMmNiNWZmYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yLHXKoOvZz-_HT5lwmBwdiq1ExVFFlqnsL-kGDwnQ0E)

Mac环境 M2

**Comment by harry0703** [comment]
把 /MoneyPrinterTurbo/config.toml 文件夹删掉试试

**Comment by zonghua2016** [comment]
> 遇到同样的问题，求助 ![image](https://private-user-images.githubusercontent.com/21120457/321243055-420075f1-f877-4678-ae71-ef09c8e50286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTY4MjEsIm5iZiI6MTcxMjc1NjUyMSwicGF0aCI6Ii8yMTEyMDQ1Ny8zMjEyNDMwNTUtNDIwMDc1ZjEtZjg3Ny00Njc4LWFlNzEtZWYwOWM4ZTUwMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEzNDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ODEyODY2YzgzYTM5YjVmYjM3Njg3ZDdlMDMwOGU1ZjAxZmI2ZjUzNzYxOTdmYzI2ODVmNWI0ZTc5YWVkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DDaa9LNYoK5oESKUmy0S43HZac-P8PaF_wd-W42xkUQ)

已解决
解决办法：
1. 删除项目目录下的 config.toml 文件夹
2. 复制一份项目目录下的 config.example.toml 文件，并重命名为 config.toml
3. 修改 config.toml 配置文件里的相关参数
4. 删除之前生成的 docker 镜像，重新在命令行中运行 docker-compose up
