### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by yome88** [harry0703/MoneyPrinterTurbo#177]
Docker部署的，运行时遇到报错。麻烦看看

<img width="1058" alt="屏幕截图 2024-04-06 123943" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/81465019/c15975ef-80af-493c-ac67-32131fff8260">

**Comment by harry0703** [comment]
看起来是网络有问题，重试了3次都失败了
如果是在国内，需要使用VPN
