### ISSUE TITLE
'***' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by renjiankun12** [harry0703/MoneyPrinterTurbo#178]
进入项目根目录后运行webui.bat一直提示我 '***' 不是内部或外部命令，也不是可运行的程序
<img width="850" alt="3E333FEA-D18B-4362-99AC-AE608DAE36C6" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/37288694/190bfa1c-94cc-48d4-9847-f6f77e3b6d58">

**Comment by harry0703** [comment]
> PowerShell有一个叫做执行策略（Execution Policy）的功能，用来控制你可以在系统上执行哪些脚本。如果执行策略过于严格，可能会阻止.bat脚本的执行。

试试 
```bat
cmd.exe /c "webui.bat"
```

**Comment by harry0703** [comment]
已优化，更新代码试试
