### ISSUE TITLE
Error code：429，请问是不能用了吗？docker

### ISSUE THREAD

**Issue by zhuangzhuang3** [harry0703/MoneyPrinterTurbo#182]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/164452484/491442da-2526-4193-a1aa-b4faa357d3b9)

**Comment by zhuangzhuang3** [comment]
moonshot

**Comment by AZIL2** [comment]
同问，一直提示到达最大请求数和引擎超载。

**Comment by magicmagicspider** [comment]
同问，我也是一直提示到达最大请求数和引擎超载。也是moonshot

**Comment by KevinZhang19870314** [comment]
用的是免费的15元赠送版吧，参考[184](https://github.com/harry0703/MoneyPrinterTurbo/issues/184)。
