### ISSUE TITLE
请问这个项目最低的电脑配置是多少？

### ISSUE THREAD

**Issue by justincnn** [harry0703/MoneyPrinterTurbo#186]
在readme中没有看到对于配置的具体要求，

如果没有要求的话，是不是在vps上也能远程运行？

**Comment by harry0703** [comment]
建议4核或以上CPU
显卡没要求

在 2024年4月7日，18:52，justincnn ***@***.***> 写道：

﻿

在readme中没有看到对于配置的具体要求，

如果没有要求的话，是不是在vps上也能远程运行？
