### ISSUE TITLE
生成进度101%，然后就一直卡在那里了，生成不了

### ISSUE THREAD

**Issue by xiaobaiguo** [harry0703/MoneyPrinterTurbo#188]
![5C3D4A71-4F7D-48b3-9865-DC58BE3F4D75](https://github.com/harry0703/MoneyPrinterTurbo/assets/82757218/e0f66746-8f7e-4684-81db-1501546da948)

**Comment by harry0703** [comment]
这个问题已经优化了，可以再试试哈，感谢反馈
