### ISSUE TITLE
调用swagger接口获取不到传入的参数

### ISSUE THREAD

**Issue by fuluola** [harry0703/MoneyPrinterTurbo#189]
启动服务后，访问swagger文档，调用接口报错，看起来是参数没接受到，这是哪里的问题？
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/12377609/01d67b8d-c11a-4ffe-814f-051328e053f0)
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/12377609/8f3ae999-a5c8-4f33-951c-b6cc58d683d4)

**Comment by harry0703** [comment]
好像是参数反序列化问题，你直接拷贝swagger里面的 curl 命令执行看看？
或者把命令发到这里，看下哪个地方的错误

**Comment by fuluola** [comment]
`curl -X 'POST' 'http://47.245.61.25:8080/api/v1/videos' -H 'accept: application/json' -H 'Content-Type: application/json'  -d '{ "video_subject": "pretty girl ,smoking,on a chair", "video_aspect": "横屏 16:9（西瓜视频）", "voice_name": "女生-晓晓", "bgm_name": "random", "font_name": "STHeitiMedium 黑体-中", "text_color": "#FFFFFF", "font_size": 60, "stroke_color": "#000000", "stroke_width": 1.5 }'`
用curl 命令执行还是一样的报错

**Comment by harry0703** [comment]
参数是错误的啊，用我这个

```shell
curl --location 'http://127.0.0.1:8080/api/v1/videos' \
--header 'Content-Type: application/json' \
--data '{
    "video_subject": "生命的意义是什么",
    "video_script": "",
    "video_terms":"",
    "video_aspect": "9:16",
    "video_concat_mode": "random",
    "video_clip_duration": 5,
    "video_count": 1,
    "voice_name": "zh-CN-XiaoxiaoNeural-Female",
    "bgm_type": "random",
    "bgm_file": "",
    "bgm_volume": 0.2,
    "subtitle_enabled": true,
    "subtitle_position": "bottom",
    "font_name": "STHeitiMedium.ttc",
    "text_fore_color": "#FFFFFF",
    "text_background_color": "transparent",
    "font_size": 60,
    "stroke_color": "#000000",
    "stroke_width": 1.5,
    "n_threads": 2,
    "paragraph_number": 1
}'
```

**Comment by fuluola** [comment]
用上面这个命令执行也是一样的结果 ，params 里面一直是空
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/12377609/ae68defa-b394-4c21-baca-3924e28327e2)
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/12377609/3029d300-a20d-46b2-8434-df0c5597361a)

**Comment by fuluola** [comment]
而且通过swagger 调试接口生成的curl 命令就是那样噢
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/12377609/02e9dc0a-59e4-43e4-ae98-014a2b674897)

**Comment by harry0703** [comment]
```
git pull
pip install -r requirements.txt
```
试试看

**Comment by fuluola** [comment]
可以了 谢谢~
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/12377609/ebda3c29-0650-40f7-859c-b5ef1bcd0345)
