### ISSUE TITLE
[enhancement] 增加分步执行选项和更多细节控制 

### ISSUE THREAD

**Issue by fenglui** [harry0703/MoneyPrinterTurbo#19]
整个生成环节分为

1. 主题文本生成，辅助视频检索关键字生成
2. 视频下载、语音合成

目前 1 => 2  是一键完成的

是否在UI提供选项，预览 1 的结果，然后再由用户觉得是否执行 2

另外建议增加 1 的控制，增加高级设置。

增加更细致的控制，在llm生成中，用户可以加入对提示模板的控制。因为，最稳定的api调用可能需要使用一些本地开源部署的模型，这些模型输出期望的文本内容，非常依赖于系统提示词。

比如，增加assistant，system角色的注入，将其作用于llm.py

```python
        messages=[
            {"role": "system", "content": "You are a video script generator. "},
            {"role": "assistant", "content": "请至少输出100个字的回复，"},
            {"role": "user", "content": prompt}
        ],
```
        
用户可以修改生成的text

**Comment by harry0703** [comment]
做了优化，可以更新代码试试

**Comment by fenglui** [comment]
太给力了
