### ISSUE TITLE
是什么原因报错呢?

### ISSUE THREAD

**Issue by soleillight** [harry0703/MoneyPrinterTurbo#190]
![Snipaste_2024-04-08_12-23-20](https://github.com/harry0703/MoneyPrinterTurbo/assets/87410957/651c10b1-817c-40f9-82b7-de720573f3fb)

**Comment by soleillight** [comment]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/87410957/be588a91-ace5-477c-b260-66bc48b8b72c)

**Comment by harry0703** [comment]
> TOMLDecodeError: Invalid value (at line 7)
应该就是 `pexels_api_keys` 配置格式不对导致的，仔细看下配置说明和示例
