### ISSUE TITLE
合成视频的时候报这个错误

### ISSUE THREAD

**Issue by okmija** [harry0703/MoneyPrinterTurbo#192]
![QQ20240408-145222](https://github.com/harry0703/MoneyPrinterTurbo/assets/19278224/887fc176-6d7e-4805-bc8d-6f08f426b7f6)
合成视频的时候报这个错误convert-im6.q16: attempt to perform an operation not allowed by the security policy

 ImageMagick已经安装了

**Comment by harry0703** [comment]
看这个FAQ：

https://github.com/harry0703/MoneyPrinterTurbo?tab=readme-ov-file#imagemagick%E7%9A%84%E5%AE%89%E5%85%A8%E7%AD%96%E7%95%A5%E9%98%BB%E6%AD%A2%E4%BA%86%E4%B8%8E%E4%B8%B4%E6%97%B6%E6%96%87%E4%BB%B6tmptmpur5hyytotxt%E7%9B%B8%E5%85%B3%E7%9A%84%E6%93%8D%E4%BD%9C
