### ISSUE TITLE
流量异常,请尝试更换网络环境

### ISSUE THREAD

**Issue by fergushoang** [harry0703/MoneyPrinterTurbo#197]
I received this message when running "流量异常,请尝试更换网络环境"

![2024-04-08_17-21](https://github.com/harry0703/MoneyPrinterTurbo/assets/57897112/a9d0140e-c3be-475e-bb1b-4e73ace361df)

**Comment by harry0703** [comment]
你是用的moonshot么？建议多试几次吧，可能服务商有什么安全机制。
或者你用GPT-3.5吧，openai已经免费了，看文档里面的说明，如何配置
