### ISSUE TITLE
视频下载错误

### ISSUE THREAD

**Issue by wangsai008** [harry0703/MoneyPrinterTurbo#20]
failed to download video: https://player.vimeo.com/progressive_redirect/playback/452468144/rendition/1080p/file.mp4?loc=external&oauth2_token_id=1747418641&signature=119a6cede599f793db17066b3c1ce57a77cddb860ab1607035c99b5ff8560a4f, HTTPSConnectionPool(host='player.vimeo.com', port=443): Max retries exceeded with url: /progressive_redirect/playback/452468144/rendition/1080p/file.mp4?loc=external&oauth2_token_id=1747418641&signature=119a6cede599f793db17066b3c1ce57a77cddb860ab1607035c99b5ff8560a4f (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

**Comment by harry0703** [comment]
请开VPN，全局流量
