### ISSUE TITLE
合成视频, log显示完成, 但是没有 combined 的最终视频.

### ISSUE THREAD

**Issue by 7mue3ttT** [harry0703/MoneyPrinterTurbo#204]
<img width="1528" alt="image" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/77006832/ba7c3d05-9910-4a2e-946c-08905d236451">

**Comment by harry0703** [comment]
请问你的问题解决了吗？

**Comment by 7mue3ttT** [comment]
没有,我怀疑是视频太长了.
我这几天合成时间长度短一些的视频, 是正常的.

**Comment by winsphinx** [comment]
我也是一样的问题，有音频文件，但没有视频文件，虽然提示有，不知道怎么处理？
我也找不到时间短一点在那里控制

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/5674054/fbfa5cbd-a937-4c6c-b3fe-57499b5d74cd)
