### ISSUE TITLE
429错误，输入视频主题后点击生成视频文案和关键词就报错

### ISSUE THREAD

**Issue by vampirejo** [harry0703/MoneyPrinterTurbo#208]
RateLimitError: Error code: 429 - {'error': {'message': 'max request per minute reached: 3, please try again after 1 seconds', 'type': 'rate_limit_reached_error'}}

**Comment by vampirejo** [comment]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/46047122/0a4a9101-38f6-4966-9078-d1aa255e531e)

**Comment by dongw5554** [comment]
大模型api调用有限制，是不是用的moonshot？是的话，就充值吧……充完就好了！我就是这样解决的………………

**Comment by vampirejo** [comment]
> 大模型api调用有限制，是不是用的moonshot？是的话，就充值吧……充完就好了！我就是这样解决的………………

可我刚用啊，moonshot后台查看还没用过限额

**Comment by dongw5554** [comment]
> > 大模型api调用有限制，是不是用的moonshot？是的话，就充值吧……充完就好了！我就是这样解决的………………
> 
> 我可以刚用啊，moonshot 后台查看还没有用过入侵

你看一下：moonshot api后台，有限制，和你的报错匹配。

**Comment by harry0703** [comment]
[OpenAI宣布ChatGPT里面3.5已经免费了](https://openai.com/blog/start-using-chatgpt-instantly)，有开发者将其封装成了API，可以直接调用

**确保你安装和启动了docker服务**，执行以下命令启动docker服务
```shell
docker run -p 3040:3040 missuo/freegpt35
```
启动成功后，修改 `config.toml` 中的配置
- `llm_provider` 设置为 `openai`
- `openai_api_key` 随便填写一个即可，比如 '123456'
- `openai_base_url` 改为 `http://localhost:3040/v1/`
- `openai_model_name` 改为 `gpt-3.5-turbo`

**Comment by dongw5554** [comment]
哈哈哈，大佬推荐使用免费的！多谢。

**Comment by iqilu2012** [comment]
> [OpenAI宣布ChatGPT里面3.5已经免费了](https://openai.com/blog/start-using-chatgpt-instantly)，有开发者将其封装成了API，可以直接调用
> 
> **确保你安装和启动了docker服务**，执行以下命令启动docker服务
> 
> ```shell
> docker run -p 3040:3040 missuo/freegpt35
> ```
> 
> 启动成功后，修改 `config.toml` 中的配置
> 
> * `llm_provider` 设置为 `openai`
> * `openai_api_key` 随便填写一个即可，比如 '123456'
> * `openai_base_url` 改为 `http://localhost:3040/v1/`
> * `openai_model_name` 改为 `gpt-3.5-turbo`

2024-04-09 17:53:00 Error refreshing session ID, retrying in 1 minute...
2024-04-09 17:53:00 If this error persists, your country may not be supported yet.
2024-04-09 17:53:00 If your country was the issue, please consider using a U.S. VPN.
2024-04-09 17:55:05 Error refreshing session ID, retrying in 1 minute...
2024-04-09 17:55:05 If this error persists, your country may not be supported yet.
2024-04-09 17:55:05 If your country was the issue, please consider using a U.S. VPN.

**Comment by harry0703** [comment]
@iqilu2012 可能要换个区域

> If your country was the issue, please consider using a U.S. VPN.

**Comment by vampirejo** [comment]
大佬求帮忙看下，现在报错502
InternalServerError: Error code: 502

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/46047122/772da141-9814-4b73-85e6-12e229794a07)

**Comment by harry0703** [comment]
依旧是网络问题，无法请求大模型，建议你用国内的模型吧

**Comment by vampirejo** [comment]
感谢大佬，已经解决了
