### ISSUE TITLE
选择竖屏可以生成，选择横屏点击生成会报错

### ISSUE THREAD

**Issue by leizusun** [harry0703/MoneyPrinterTurbo#213]
RetryProviderError: RetryProvider failed: FreeGpt: UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 75-76: unexpected end of data ChatgptNext: ClientResponseError: 429, message='Too Many Requests', url=URL('https://chat.fstha.com/api/openai/v1/chat/completions') Chatgpt4Online: MissingRequirementsError: Install "undetected_chromedriver" and "platformdirs" package You: MissingRequirementsError: Install "curl_cffi" package

**Comment by harry0703** [comment]
> ClientResponseError: 429, message='Too Many Requests',

要等会再试，超过配额了，或者你换个 `llm_provider`
