### ISSUE TITLE
writing 步骤报错了

### ISSUE THREAD

**Issue by soleillight** [harry0703/MoneyPrinterTurbo#214]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/87410957/5b8f8d0f-72d2-4e40-8b04-b5cdeff843c8)

**Comment by harry0703** [comment]
建议你把错误信息发完整
看起来是ffmpeg报错了，你看看ffmpeg版本是不是太低了

**Comment by soleillight** [comment]
好的



在 2024-04-10 10:15:41，"Harry" ***@***.***> 写道：

建议你把错误信息发完整
看起来是ffmpeg报错了，你看看ffmpeg版本是不是太低了
