### ISSUE TITLE
连续调用接口`/api/v1/videos`，生成视频错误

### ISSUE THREAD

**Issue by KevinZhang19870314** [harry0703/MoneyPrinterTurbo#217]
连续调用`/api/v1/videos`接口多次（差不多每隔几秒调用一次，连续4~5次），只有一个生成成功了，其他的都失败。同时发现一个奇怪的现象，临时mp3文件(类似`final-1.mp4.tempTEMP_MPY_wvf_snd.mp3`)生成到根目录了（结束后又自动删掉）。

附上log：
[2024-04-10.txt](https://github.com/harry0703/MoneyPrinterTurbo/files/14926706/2024-04-10.txt)

**Comment by KevinZhang19870314** [comment]
看起来是生成video临时文件，多次调用接口后，文件名没有唯一命名，导致r/w冲突。

**Comment by harry0703** [comment]
收到，我看下这个问题

**Comment by KevinZhang19870314** [comment]
https://github.com/harry0703/MoneyPrinterTurbo/blob/c866c4a38327f380669d985f8dc878601ae10123/app/services/video.py#L243

有没有可能是video.py文件中这个对象`VideoFileClip`处理完没有close掉？对moviepy这个库不是太了解，纯猜测。:)

**Comment by harry0703** [comment]
已经定位到原因，修改好了，在测试中，等会就提交

**Comment by harry0703** [comment]
已提交代码，麻烦再试试看，顺便优化了性能，减少了一次ffmpeg编码，速度有很大的提升
有问题欢迎再次反馈

**Comment by KevinZhang19870314** [comment]
试过了，没有出现错误了，谢谢！

**Comment by harry0703** [comment]
@KevinZhang19870314 我看你回复了很多的issue，太感谢了啊！~
看了你的github页面，很高产，很活跃👍
前几天email（github首页公布的email）尝试联系了一下你，没联系上：）

**Comment by KevinZhang19870314** [comment]
@harry0703 主要是对这个项目比较感兴趣，正好自己对python有些许了解，知道的问题就帮忙回复了，另外有些功能觉得有必要就提了pr，如果可以的话可以建个微信或者qq群这样沟通起来效率高一些（大多数还是国人提的issues）。

**Comment by harry0703** [comment]
创建了一个微信群，确实是方便一些
https://harryai.cc/moneyprinterturbo   【里面有群二维码】
