### ISSUE TITLE
combine_videos有问题

### ISSUE THREAD

**Issue by qing-tian-meng-ying** [harry0703/MoneyPrinterTurbo#223]
![1712754727523](https://github.com/harry0703/MoneyPrinterTurbo/assets/113198227/ced54641-cad2-4cee-8ed0-636c79b5c67c)
多次尝试生成视频的时候在combine_videos过程中断退出。

**Comment by harry0703** [comment]
试试升级pillow依赖库
```
pip install opencv-python
pip install pillow~=10.3.0
```
