### ISSUE TITLE
刚启动就出现了一下问题，请大神执教

### ISSUE THREAD

**Issue by Liumartin888** [harry0703/MoneyPrinterTurbo#226]
![error](https://github.com/harry0703/MoneyPrinterTurbo/assets/95725776/32a972fa-08d0-4759-984c-4f87d9c2407f)

**Comment by lnwqh** [comment]
没配置大模型key 默认openai。修改配置文件\MoneyPrinterTurbo\config.toml         如：# 如果你没有 OPENAI API Key，可以使用 g4f 代替，或者使用国内的 Moonshot API
    # If you don't have an OPENAI API Key, you can use g4f instead

    # 支持的提供商 (Supported providers):
    #   openai
    #   moonshot (月之暗面)
    #   oneapi
    #   g4f
    #   azure
    #   qwen (通义千问)
    #   gemini
    llm_provider="ollama"

**Comment by cnleaf8600** [comment]
修改配置文件 使用  g4f    APIKEY  随便填写

**Comment by harry0703** [comment]
你使用OPENAI的服务，但是你没有获得 gpt-4-turbo的权限，或者你可以改为3.5试试
到这里查看你的授权模型：https://platform.openai.com/account/limits
