### ISSUE TITLE
Cannot connect to host speech.platform.bing.com

### ISSUE THREAD

**Issue by c2dp** [harry0703/MoneyPrinterTurbo#230]
Cannot connect to host speech.platform.bing.com
直接访问，显示：
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0d6cXZgAAAAACXg5W07VdTYYnIrW8WWZBSEtCRURHRTA2MTcARWRnZQ==
有遇到过这个问题吗

**Comment by harry0703** [comment]
网络问题，翻墙即可，全局流量模式
