### ISSUE TITLE
素材拼接的时候，能否选择是用GPU还是CPU吗？

### ISSUE THREAD

**Issue by Test-Jim** [harry0703/MoneyPrinterTurbo#234]
我测试了大量的素材合成，CPU和GPU的使用基本都是空的，内存占用反而很高
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/25148209/8fd08efa-d8bf-4d5e-8a6f-1a44ce50f178)

我看到只有whisper是可以用GPU的

**Comment by Test-Jim** [comment]
然后最后报了这个错，文件目录也变成了这样
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/25148209/eb3a9e16-5745-4421-a377-e9afcc4b1058)
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/25148209/df5e2eed-7b32-4782-a628-a9eff92df674)

**Comment by harry0703** [comment]
收到，我定位下原因，感谢反馈

**Comment by harry0703** [comment]
你可以把这整个文件夹压缩后发个我么（可能有点大，不知道这里能不能上传上来），还有 这个bgm文件

<img width="572" alt="image" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/4928832/28b396b4-996c-422c-9145-cbaedb8c3855">

**Comment by Test-Jim** [comment]
> 可能有点大，不知道这里能不能上传上
[test.zip](https://github.com/harry0703/MoneyPrinterTurbo/files/14953022/test.zip)
combined这个文件太大了，没法传，我上传了发送请求的报文，大概率能在你那边复现的吧。
另外我想知道一下，writing的时候 速度很慢，有没有办法提高？

**Comment by harry0703** [comment]
该问题已修复，可以更新代码试试
