### ISSUE TITLE
合并视频时报错

### ISSUE THREAD

**Issue by Vinci0007** [harry0703/MoneyPrinterTurbo#236]
![屏幕截图 2024-04-11 202340](https://github.com/harry0703/MoneyPrinterTurbo/assets/39933794/d5acca49-c876-43fb-99ea-715f9c08f358)

**Comment by harry0703** [comment]
看看 ffmpeg 的版本是多少

**Comment by Vinci0007** [comment]
您好：
ffmpeg version: 2024-04-10-git-0e4dfa4709
ImageMagick 7.1.1-29

**Comment by Vinci0007** [comment]
@harry0703 
您好：
ffmpeg version: 2024-04-10-git-0e4dfa4709
ImageMagick 7.1.1-29

**Comment by harry0703** [comment]
我优化了一下代码，你更新试试看，应该是OK了

**Comment by Vinci0007** [comment]
好的，我试试，多谢
