### ISSUE TITLE
docker-compose出错了，这个怎么改

### ISSUE THREAD

**Issue by lzhdelife** [harry0703/MoneyPrinterTurbo#239]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "x-common-volumes". Valid top-level sections for this Compose file are: version, services, networks, volumes, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
![1712849349173](https://github.com/harry0703/MoneyPrinterTurbo/assets/44942584/68f6c98e-6dfc-4c3e-bcbe-4b368279387f)

**Comment by harry0703** [comment]
把 docker-compose.yml 的第一行 version 删掉看看
