### ISSUE TITLE
6000字的长文本生成视频报错

### ISSUE THREAD

**Issue by lingkongyueqi** [harry0703/MoneyPrinterTurbo#243]
![QQ截图20240412093739](https://github.com/harry0703/MoneyPrinterTurbo/assets/79496892/a5264079-bac0-4e5c-8a02-0b65ce29a868)

**Comment by lingkongyueqi** [comment]
好像要开VPN才行，那为什么短文本不开VPN也可以

**Comment by harry0703** [comment]
这个是模型下载出错了，网络原因，国内无法访问huggingface网站

建议你**更新代码**，然后参照 https://github.com/harry0703/MoneyPrinterTurbo?tab=readme-ov-file#%E5%AD%97%E5%B9%95%E7%94%9F%E6%88%90-

下载和安装模型，再试试，应该就可以了
