### ISSUE TITLE
在合成 长视频   的时候，能否新增pycuda  ，用GPU加速合成，效率会快很多

### ISSUE THREAD

**Issue by Test-Jim** [harry0703/MoneyPrinterTurbo#245]
我测试了14分钟的视频。花了20多分钟，而且是内存基本吃满的情况下，，，，

**Comment by harry0703** [comment]
看这个 《如果有GPU卡的，可以用ffmpeg的编码加速视频合成codec='h264_nvenc'》https://github.com/harry0703/MoneyPrinterTurbo/issues/171
