### ISSUE TITLE
拉取完新代码，重新执行pip install -r requirements.txt，配置文件修改为llm_provider="g4f"，点击“开始生成视频”报错如下：

### ISSUE THREAD

**Issue by javatomatos** [harry0703/MoneyPrinterTurbo#25]
You: NestAsyncioError: Use "create_async" instead of "create" function in a running event loop. Or use "nest_asyncio" package. Chatgpt4Online: NestAsyncioError: Use "create_async" instead of "create" function in a running event loop. Or use "nest_asyncio" package.

**Comment by harry0703** [comment]
更新代码后再试试看
