### ISSUE TITLE
发现在recloud.cn上的视频就是两三个短视频不停来回切换来组成长一点的视频，本地安装的项目也是这样处理的么？

### ISSUE THREAD

**Issue by toneytang** [harry0703/MoneyPrinterTurbo#276]
发现在recloud.cn上的视频就是两三个短视频不停来回切换来组成长一点的视频，本地安装的项目也是这样处理的么？

**Comment by harry0703** [comment]
本地不会，可能 https://reccloud.cn 的有bug，我反馈给他们一下 :)

**Comment by toneytang** [comment]
感谢回答。本地运行的时候，视频素材是AI生成的，还是从某个云端素材库拉的视频素材？可否部分使用本地素材？

**Comment by harry0703** [comment]
是云端素材库匹配的，本地的素材还在开发中
