### ISSUE TITLE
视频片段最大时长，参数是否错误？

### ISSUE THREAD

**Issue by w280740130** [harry0703/MoneyPrinterTurbo#292]
视频片段最大时长，参数是否错误？

变成了 最小时长！

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/13121515/3ca59dfc-0bbb-401f-adec-d2dbb74d5497)

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/13121515/789651b9-a0ae-4065-8245-3e4f9ff70b8a)

**Comment by harry0703** [comment]
没有错误，是正确的逻辑，在不同的地方，这个参数代表的含义不一样
