### ISSUE TITLE
Docker 部署无法使用微软新语音

### ISSUE THREAD

**Issue by oicid** [harry0703/MoneyPrinterTurbo#293]
使用当前配置 build 之后，无法使用微软新语音，报错如下：

```
azure v2 speech synthesis error: Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
```

[经查](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cdebian%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-python)，这是由于 `azure-cognitiveservices-speech` 目前仅支持 `openssl-1.1` 的缘故，而本项目依赖的镜像 `python:3.10-slim` 底层是 `Debian 12`，已经默认不支持 `openssl-1.1`。如果从源码编译`openssl-1.1`，则在安装相关依赖`git`和`ffmpeg`时又会自动安装`openssl-3.0`，导致微软新语音仍无法运行。

建议在配置 Docker 时使用旧一点的镜像，比如 `Debian 10/11`、`Ubuntu 20.04`等。

**Comment by oicid** [comment]
经测，将 `python:3.10-slim`换为`python:3.10-bullseye`能解决上述问题。此时得到的镜像大小约为 2.5GB。

**Comment by harry0703** [comment]
感谢反馈👍
