### ISSUE TITLE
能否使用本地自建的模型，应该如何设置

### ISSUE THREAD

**Issue by wc1322000** [harry0703/MoneyPrinterTurbo#296]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/16535458/4d9240fe-da5a-4ce2-b59e-bff4d9ac8d44)
API Key，Pexels API Key都是随便填的123456.
Base Url：http://127.0.0.1:11434是我的模型地址。
点击生成会报错。APIConnectionError: Connection error.
是不是我的设置有错？

**Comment by harry0703** [comment]
可以的，一般这样设置
```
openai_api_key = "xxxx"
openai_base_url = "http://localhost:11434/v1/"
openai_model_name = "llama3:8b"
```
