### ISSUE TITLE
How to use other language as video subtitle and dub

### ISSUE THREAD

**Issue by pangchewe** [harry0703/MoneyPrinterTurbo#297]
It's seem like I can't use TH language for a video but i see all voice that are support it have TH in it
How to enable all language that available?

**Comment by pangchewe** [comment]
Solved. Just edit main.py

**Comment by harry0703** [comment]
Yes, I have added it. you just need to update the code :)

**Comment by userbox020** [comment]
hello, im using the docker container how do i enable all the voices options?
