### ISSUE TITLE
出现无法下载视频问题

### ISSUE THREAD

**Issue by Illusionist0** [harry0703/MoneyPrinterTurbo#30]
failed to download video: https://player.vimeo.com/progressive_redirect/playback/569219784/rendition/1080p/file.mp4?loc=external&oauth2_token_id=1747418641&signature=1da7681f47aacaba07c57b8efdfd1471332b878da968a944ef63fb8df8acd82c, HTTPSConnectionPool(host='player.vimeo.com', port=443): Max retries exceeded with url: /progressive_redirect/playback/569219784/rendition/1080p/file.mp4?loc=external&oauth2_token_id=1747418641&signature=1da7681f47aacaba07c57b8efdfd1471332b878da968a944ef63fb8df8acd82c (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff51c35a3b0>, 'Connection to player.vimeo.com timed out. (connect timeout=None)'))
各位大佬们，我发现我收集到一定视频后就会无法下载了，这是因为下载太多被block了吗，还是因为什么？

**Comment by harry0703** [comment]
要开VPN，国内无法直接访问

**Comment by Illusionist0** [comment]
> 要开VPN，国内无法直接访问

大佬，开了还是下不了，要在config里设置代理吗？我浏览器可以访问，但是后台跑不了诶

**Comment by harry0703** [comment]
那说明你的VPN只是代理了浏览器的流量，你需要设置为 `全局代理`
或者你也可以在 `config.toml` 里面，设置 `http` 和 `https` 的网络代理
```toml
[pexels.proxies]
        ### Use a proxy to access the Pexels API
        ### Format: "http://<username>:<password>@<proxy>:<port>"
        ### Example: "http://user:pass@proxy:1234"
        ### Doc: https://requests.readthedocs.io/en/latest/user/advanced/#proxies
        # http = "http://10.10.1.10:3128"
        # https = "http://10.10.1.10:1080"
```
