### ISSUE TITLE
手动部署或docker部署都无法访问127.0.0.1:8080/docs

### ISSUE THREAD

**Issue by zzu402** [harry0703/MoneyPrinterTurbo#300]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/18510098/f71e355d-7a4f-405c-a169-36d1d10ecf47)

**Comment by harry0703** [comment]
把这个 `api.bat` 放到项目根目录下面，双击启动API服务

[api.bat.zip](https://github.com/harry0703/MoneyPrinterTurbo/files/15060990/api.bat.zip)

**Comment by dwgeneral** [comment]
Mac 和 Linux 也是一样的问题，打印输出  INFO | "./main.py:6": <module> - start server, docs: http://127.0.0.1:8502/docs
但是也无法访问

**Comment by dwgeneral** [comment]
> Mac 和 Linux 也是一样的问题，打印输出 INFO | "./main.py:6": - start server, docs: http://127.0.0.1:8502/docs 但是也无法访问

已经解决，在 docker-compose.yml 里需要导出 8502 端口

**Comment by ransongjie** [comment]
"8502:8080"
