### ISSUE TITLE
docker-compose up报错

### ISSUE THREAD

**Issue by MuYi086** [harry0703/MoneyPrinterTurbo#305]
不使用代理卡在  `failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: docker.io/library/python:3.10-slim-bullseye not found
`

使用US的代理卡在 `failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head "https://mirror.ccs.tencentyun.com/v2/library/python/manifests/3.10-slim-bullseye": dial tcp: lookup mirror.ccs.tencentyun.com: no such host`

怎么办

**Comment by harry0703** [comment]
用VPN试试
