### ISSUE TITLE
运行不了，ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by hackyinge** [harry0703/MoneyPrinterTurbo#31]
ModuleNotFoundError: No module named 'app'
Traceback:
File "D:\pinokio\bin\miniconda\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "G:\MoneyPrinterTurbo\webui\Main.py", line 7, in <module>
    from app.models.schema import VideoParams, VideoAspect, VoiceNames

**Comment by harry0703** [comment]
1，进入到项目根目录
2，执行 webui.bat

如果提示找不到模块
可以打开 `webui.bat`，修改一下 `PYTHONPATH` 的路径为你项目的绝对路径，再试试看

**Comment by TheDevelolper** [comment]
@harry0703 I've done exactly this in linux, I set PYTHONPATH=/my/path.. then I ran and I see the same error. I even put a print current working directory code into the main.py and it showed the correct dir. When I echo the directory again it shows the correct directory.

This didn't fix the issue unfortunately.
