### ISSUE TITLE
Ollama Set Up

### ISSUE THREAD

**Issue by Jared1407** [harry0703/MoneyPrinterTurbo#314]
Running ollama on localhost:11434, I get the following error:

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/98782318/15ecb8ee-954e-4562-ac6a-acc6199ce671)

Here is the LLM Setup: 
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/98782318/fe0bd892-fb35-49c2-baff-72b4edd06227)

And here is the ollama service running:
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/98782318/79e9034b-d204-4596-b28d-54f144e9b7c3)

Any help would be greatly appreciated!!

**Comment by harry0703** [comment]
Are you deploying with **Docker**?
If it's deployed with Docker, the base URL should be `http://host.docker.internal:11434/`

**Comment by Jared1407** [comment]
Ok that worked, however now in the Ollama logs the call to /chat/completions returns a 404 error

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/98782318/82d4c3bf-c802-4a39-95ac-2ba07196b9ef)

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/98782318/f06aef7f-3715-44da-8b6e-255687b67c70)

**Comment by harry0703** [comment]
The full base url should be:
`http://host.docker.internal:11434/v1`

**Comment by Jared1407** [comment]
The same error shows up, should it not be calling the Ollama api with /api/generate? 
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/98782318/61f7f80d-fe12-449c-bce6-e3058641a1f5)
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/98782318/24048f9e-4866-4b9d-9f0b-ce1354ab3202)
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/98782318/63a61cf3-e472-42ec-9be8-9ba2bfb1ac2b)

**Comment by harry0703** [comment]
you should run command `ollama list` to check the models you installed.
and then set a valid model name.

**Comment by Sogrey** [comment]
http://host.docker.internal:11434/v1
