### ISSUE TITLE
why the memory usage always increased, do we have recommended device configure? 

### ISSUE THREAD

**Issue by dwgeneral** [harry0703/MoneyPrinterTurbo#316]
from 2G increased to 7G after only did a few tasks
![截屏2024-04-25 18 20 23](https://github.com/harry0703/MoneyPrinterTurbo/assets/8654993/e384e4b0-f056-410d-b573-7f9fa94ed6a3)

**Comment by harry0703** [comment]
Are you using the latest code?
There was a memory leak bug in previous versions, but it has been fixed in the latest code.

**Comment by dwgeneral** [comment]
got it, I'll try it, thanks bro
