### ISSUE TITLE
出现名为    AttributeError: 'NoneType' object has no attribute 'get'    的错误

### ISSUE THREAD

**Issue by SimmyCHN** [harry0703/MoneyPrinterTurbo#317]
代码描述：

Traceback:
File "D:\MoneyPrinterTurbo\lib\python\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "D:\MoneyPrinterTurbo\MoneyPrinterTurbo\webui\Main.py", line 437, in <module>
    video_files = result.get("videos", [])

是不是我的模型秘钥不对，还是什么错误导致的啊

**Comment by harry0703** [comment]
要复制完整的错误，你这个提供的信息太少了
一般原因：
1，pelexs的api key错了
2，合成声音选错了，可能你的文案是中文，但是语音没有选中文
3，网络问题，开VPN

**Comment by SimmyCHN** [comment]
大佬们，我昨天解决好了，向你们汇报一下：我把音频的声音模型换了一个，这个问题就消失了。
有个想法：就是视频如果能花里胡哨一点就好了。怎么讲…现在的视频太板正了：人物出现的比重占视频时长太多，并且总是西方人。
想法：生成视频的素材api来自非pelexs，模型的api能来自未来的sora就好了（sora未来能申请api的话），让视频生成的画面更有悬念和绚丽就好了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月26日 10:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [harry0703/MoneyPrinterTurbo] 出现名为    AttributeError: 'NoneType' object has no attribute 'get'    的错误 (Issue #317) |

Closed #317 as completed.

**Comment by harry0703** [comment]
感谢反馈~ 不断优化中。。。

**Comment by SimmyCHN** [comment]
应该谢谢大佬们



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月26日 10:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [harry0703/MoneyPrinterTurbo] 出现名为    AttributeError: 'NoneType' object has no attribute 'get'    的错误 (Issue #317) |

感谢反馈~ 不断优化中。。。
