### ISSUE TITLE
Help! 什么是 “”模型名称 (需要到大模型提供商的后台确认被授权的模型名称)"

### ISSUE THREAD

**Issue by glennchina** [harry0703/MoneyPrinterTurbo#323]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/19704749/e3a5368e-dc4c-4cbe-bfa9-3c2f549c29ae)
这个在openai的哪里能找到？

**Comment by harry0703** [comment]
这里有说明，请查看

<img width="608" alt="image" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/4928832/57a5b819-75ac-4de6-86f0-6584e837a34b">
