### ISSUE TITLE
VPS上docker部署，执行出错了

### ISSUE THREAD

**Issue by moneytree520** [harry0703/MoneyPrinterTurbo#329]
![{7B1AA911-E2A3-46f6-BB56-6C6531DD31F9}](https://github.com/harry0703/MoneyPrinterTurbo/assets/77653761/66fe9d59-63f8-4777-be9c-7854067b6030)
不知道是何原因，但是VPS上能ping通这个deb.debian.org

**Comment by changingshow** [comment]
遇到同样的错误了，你解决了吗？我的linux系统中 没有apt 包管理用的是yum，不知道是不是这个原因。

**Comment by harry0703** [comment]
这个就是典型的网络问题，建议使用镜像源，比如清华的，或者阿里的

**Comment by moneytree520** [comment]
> 遇到同样的错误了，你解决了吗？我的linux系统中 没有apt 包管理用的是yum，不知道是不是这个原因。

我的是纯IPV6的vps，DNS加了nameserver 8.8.8.8  nameserver 8.8.4.4就可以了
