### ISSUE TITLE
合成字幕ImageMagick   一直报错

### ISSUE THREAD

**Issue by sssssssssh** [harry0703/MoneyPrinterTurbo#33]
已经安装，切已经配置了路径。
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/54253683/bc8beef0-4706-4164-b222-6530de370262)
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/54253683/bfe6a959-92f5-475d-b527-369d22efab38)
但是换了几个版本，重新安装还是报错

**Comment by harry0703** [comment]
你按照 **示例配置** 里面提供的 `下载地址`，下载安装

[https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-29-Q16-x64-static.exe](https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-29-Q16-x64-static.exe)

别用动态库的版本，用静态库，应该就可以了

**Comment by sssssssssh** [comment]
> 你按照 **示例配置** 里面提供的 `下载地址`，下载安装
> 
> https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-29-Q16-x64-static.exe
> 
> 别用动态库的版本，用静态库，应该就可以了

还是不行，我最开始就是用的静态的

**Comment by sssssssssh** [comment]
已解决，去除中文路径。
