### ISSUE TITLE
建议：生成视频的网络素材来源支持自定义。

### ISSUE THREAD

**Issue by carveybunt** [harry0703/MoneyPrinterTurbo#335]
您的网络素材来源YouTube，素材内部大部分都是非国人的。不知道是否考虑后期支持自定义素材来源，这样国人就可以从国内视频平台获取相关的网络素材了。

**Comment by alexdo83** [comment]
SUPPORT COMING SOON:

![1](https://github.com/harry0703/MoneyPrinterTurbo/assets/25850343/a408085c-099e-4f1c-8fd5-3041cb6895f4)

**Comment by Weststreet** [comment]
> SUPPORT COMING SOON:
> 
> ![1](https://private-user-images.githubusercontent.com/25850343/327393427-a408085c-099e-4f1c-8fd5-3041cb6895f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Njc2NTEsIm5iZiI6MTcxNDg2NzM1MSwicGF0aCI6Ii8yNTg1MDM0My8zMjczOTM0MjctYTQwODA4NWMtMDk5ZS00ZjFjLThmZDUtMzA0MWNiNjg5NWY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDAwMDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MDM4YTU0MTdiMmUyNzM5YjQ4NzQyNzJiMDliZmE1N2FhMWE0N2RmNmJhZTdkYzAzZTdkMWMyNTAyYjlmMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZyDsBybiDtt3xlMTG9BtoQ-7paP3vSRuB_b3z4wn6oc)
这个功能太棒了
