### ISSUE TITLE
在获取video资源时，搜索结果为0，导致计算时长时为除0报错

### ISSUE THREAD

**Issue by bofengsun** [harry0703/MoneyPrinterTurbo#34]
虽然没有运行成功，还是要给作者点个赞，看了代码真的是优秀，逻辑清晰，代码整洁，注释完善，很不错，加油。
最后贴个错误图片：
![1711002816319](https://github.com/harry0703/MoneyPrinterTurbo/assets/57429891/d391d3d3-9920-4591-b9a1-7578bdf0fbbb)

**Comment by harry0703** [comment]
应该是没有找到相关的资源，可以换个主题
因为是使用的GPT自动生成的关键词，**有时候生成的关键词比较长**，导致检索不到视频
我后面会优化下

**Comment by harry0703** [comment]
做了优化，可以更新代码试试
