### ISSUE TITLE
使用 One API 报错

### ISSUE THREAD

**Issue by AuYuHui** [harry0703/MoneyPrinterTurbo#345]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/38815121/7f156ae3-8bb2-4494-bad1-3ecbdd73dd3e)

**Comment by AuYuHui** [comment]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/38815121/087592b2-40e0-4207-9c2f-da90404b2ca5)

**Comment by harry0703** [comment]
这个应该是 base url设置错了

**Comment by AuYuHui** [comment]
> 这个应该是 base url设置错了

URL 是对的
