### ISSUE TITLE
视频生成失败

### ISSUE THREAD

**Issue by auroralzone** [harry0703/MoneyPrinterTurbo#347]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/42070770/7b40f0de-a194-456d-b65f-372165fa7d44)

**Comment by auroralzone** [comment]
global VPN 无法配合 moonshot ?
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/42070770/8889c997-3c72-4af8-8ed9-6657c85b35b1)

**Comment by auroralzone** [comment]
成功了！

`改地区`就行

**Comment by StealFeam** [comment]
@auroralzone 改哪里的地区？

**Comment by harry0703** [comment]
@StealFeam 他这个报错，是因为文案是中文的，但是选的语音合成是 en英文，改成zh中文就行了

**Comment by auroralzone** [comment]
> @auroralzone 改哪里的地区？

梯子。我用moonshot，`新加坡`完美成功
