### ISSUE TITLE
gpt生成文本素材，能不能多一个修改的步骤，ai生成的随机性太强了，质量不好控制

### ISSUE THREAD

**Issue by mumutoy** [harry0703/MoneyPrinterTurbo#35]
能不能在gpt帮忙生成文案的时候，生成搜图的关键词和对应的文案，可以支持自定义修改吗，这一步可以手动修改一下，在进行下一步就好了，现在生成的文案随机性太强了，不一定能生成比较好的文案内容。

**Comment by harry0703** [comment]
谢谢反馈，已经在优化中了

**Comment by harry0703** [comment]
做了优化，可以更新代码试试

**Comment by mumutoy** [comment]
rsp,ok了
