### ISSUE TITLE
网络正常，但无法下载视频

### ISSUE THREAD

**Issue by pagear** [harry0703/MoneyPrinterTurbo#352]
![0bc9e87b345857ce15afc2bee5b8284](https://github.com/harry0703/MoneyPrinterTurbo/assets/90494926/d60956bc-6185-4e19-94e0-59251c8524e0)
![02024195985ab42895cb6887abce69f](https://github.com/harry0703/MoneyPrinterTurbo/assets/90494926/3cb67d40-9f15-4316-bced-1ed94f16f15a)
![639d8a1756205e8a5d9d772be708988](https://github.com/harry0703/MoneyPrinterTurbo/assets/90494926/add37697-2335-4432-b74f-67c1613bfd72)

**Comment by harry0703** [comment]
日志太少了，麻烦你看下完整的日志。更好定位问题。
