### ISSUE TITLE
选择自定义背景音乐，参数还是random

### ISSUE THREAD

**Issue by lixplor** [harry0703/MoneyPrinterTurbo#358]
docker compose部署

修改背景音乐路径后按了`Enter`确认，日志输出参数仍然是random

```json
    "bgm_type": "random",
    "bgm_file": "",
    "bgm_volume": 0.2,
```

另外请教一下，docker方式的自定义背景音乐路径填写绝对路径还是相对路径？相对哪里？

**Comment by harry0703** [comment]
显示有点bug，不过这个不影响。判断逻辑是，如果有 bgm_file，会优先使用。
目前是要绝对路径，也就是你docker里面需要存在该文件
可以用外部挂载
