### ISSUE TITLE
前面几次运行可以正常生成，后面出现运行中途报错

### ISSUE THREAD

**Issue by Mr-lcx** [harry0703/MoneyPrinterTurbo#36]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/57147405/1aa27ae1-09d0-402f-bbd4-9430175a78e7)

**Comment by harry0703** [comment]
检查下字幕文件 `subtitle.srt` 生成成功没有，用记事本打开看看
如果是字幕的问题，可以在配置文件里面，把 `subtitle_provider` 改成 `whisper` 再试试看

**Comment by Mr-lcx** [comment]
试过了，还是不行
![Uploading image.png…]()

**Comment by harry0703** [comment]
做了优化，可以更新代码试试
