### ISSUE TITLE
docker 安装， 运行 docker-compose up 时提示 “ERROR: In file './docker-compose.yml', service 'x-common-volumes' must be a mapping not an array.”

### ISSUE THREAD

**Issue by michael-xgw** [harry0703/MoneyPrinterTurbo#361]
源docker-compose.yml，未做任何改动
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/51981994/b4a83ce3-1858-420c-89ba-221359d6b6d2)

**Comment by harry0703** [comment]
应该是docker的版本过低了，你升级到最新的docker应该就可以了

比如我的版本如下：
```
➜  docker -v
Docker version 24.0.7, build afdd53b4e3

➜  docker-compose -v
Docker Compose version 2.23.3
```

**Comment by michael-xgw** [comment]
奇怪，阿里云的ubuntu 20, update & upgrade 之后，apt install doker-compose 的默认安装版本竟然是 1.25.0
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/51981994/f1c8dd6b-a898-4496-b61a-b694afa12fd8)
