### ISSUE TITLE
提示没装 ImageMagick 

### ISSUE THREAD

**Issue by heihei180** [harry0703/MoneyPrinterTurbo#363]
您好，我已经安装了 ImageMagick ， 并且在config.toml 中配置了 `imagemagick_path = "C:\\Program Files (x86)\\ImageMagick-7.1.1-Q16\\magick.exe"`
但是我发现一个问题，每次启动程序后，这行代码`imagemagick_path = "C:\\Program Files (x86)\\ImageMagick-7.1.1-Q16\\magick.exe"` 就会被自动删除。
然后我生成视频的时候，会报下面的问题，搜索了issue，没找到原因是为什么，您能帮忙解答一下吗？谢谢！

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/38102241/2a01ec7b-7598-4997-81b8-89b9e92f1a04)

**Comment by harry0703** [comment]
```toml
# imagemagick_path = "C:\\Program Files (x86)\\ImageMagick-7.1.1-Q16\\magick.exe"
# 你要把配置文件前面的 `#` 去掉
imagemagick_path = "C:\\Program Files (x86)\\ImageMagick-7.1.1-Q16\\magick.exe"
```
你看看是不是没有去掉配置文件中的注释？

**Comment by harry0703** [comment]
我没法复现这个问题，你先更新代码看看。也可以直接把这个配置写死在代码里面试试

```python
# app/config/config.py
imagemagick_path = app.get("imagemagick_path", "")
if imagemagick_path and os.path.isfile(imagemagick_path):
    os.environ["IMAGEMAGICK_BINARY"] = imagemagick_path
```
