### ISSUE TITLE
生成的视频字幕是乱码怎么办？

### ISSUE THREAD

**Issue by zhangjie1425** [harry0703/MoneyPrinterTurbo#37]
<img width="431" alt="截屏2024-03-21 19 28 52" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/10610972/44f6c391-0c42-444d-adf0-73b44857224e">

**Comment by harry0703** [comment]
请检查下：
1. 打开生成的srt看看是不是正确的？
2. 是否使用了自定义的字体？该字体是否支持中文？

**Comment by mumutoy** [comment]
而且发现字幕有时候会没有生成完全，视频的后半段经常会没有字幕信息

**Comment by harry0703** [comment]
> 视频的后半段经常会没有字幕信息

该问题已优化，可以更新代码试试

**Comment by paynepang** [comment]
[https://github.com/harry0703/MoneyPrinterTurbo/issues/37#issuecomment-2016396680](url) 问题似乎还存在

**Comment by paynepang** [comment]
> > 视频的后半段经常会没有字幕信息
> 
> 该问题已优化，可以更新代码试试
script.json：
{
    "script": "方奇迈获得了一个特殊的系统。谁点他的名他就能从谁身上获得奖励。叮，你被数学老师点名，奖励，技能书《奥数掌握》。叮，你被富二代同 学点名，解锁人物，首富老爸。叮，你被体育老师点名，奖励，技能书《英语语法掌握》。等等，刚刚好像混进去了什么奇怪的东西...",
    "search_terms": [
        "funny school moments",
        "mysterious system rewards",
        "classmate interactions",
        "special skills unlocked",
        "unexpected school events"
    ]
}
------------------------------------------------
subtitle.srt：
1
00:00:00,100 --> 00:00:02,513
方奇迈获得了一个特殊的系统

2
00:00:03,087 --> 00:00:06,287
谁点他的名他就能从谁身上获得奖励

3
00:00:06,850 --> 00:00:07,100
叮

4
00:00:07,463 --> 00:00:08,887
你被数学老师点名

5
00:00:09,075 --> 00:00:09,562
奖励

------------------------------------------------------------
后半段的文字没有字幕

**Comment by shuaidiandian** [comment]
今天刚拉取下来的代码  windows系统生成的视频字幕正常  linux字幕乱码，subtitle.srt文件内容显示是正常的
