### ISSUE TITLE
Unknown method in

### ISSUE THREAD

**Issue by Root-FTW** [harry0703/MoneyPrinterTurbo#373]
esrre when unzipping the .7z version

! C:\Users\rootf\Downloads\Compressed\MoneyPrinterTurbo-Portable-Windows-1.1.9.7z: Unknown method in lib\python\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
! C:\Users\rootf\Downloads\Compressed\MoneyPrinterTurbo-Portable-Windows-1.1.9.7z: Unknown method in lib\python\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
! C:\Users\rootf\Downloads\Compressed\MoneyPrinterTurbo-Portable-Windows-1.1.9.7z: Unknown method in lib\python\Lib\site-packages\setuptools\gui-arm64.exe
! C:\Users\rootf\Downloads\Compressed\MoneyPrinterTurbo-Portable-Windows-1.1.9.7z: Unknown method in lib\python\Lib\site-packages\setuptools\cli-arm64.exe

![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/108767514/16f13a93-0dd6-4721-ae6d-fcd0d452ee3d)

**Comment by harry0703** [comment]
You need to use 7zip to unzip the .7z file.

https://www.7-zip.org/
