### ISSUE TITLE
How to download generated files on the API

### ISSUE THREAD

**Issue by sillyluna** [harry0703/MoneyPrinterTurbo#377]
How to download the generated video file, I modified the path but it seems unchanged, what settings do I need to adjust?
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/67021650/2972fa15-312f-4580-88c5-8d0a40752b3a)

**Comment by sillyluna** [comment]
请问在使用API时，如何设置下载生成的视频文件

**Comment by KevinZhang19870314** [comment]
流式的response，客户端`responseType: 'arraybuffer'`就可以接收了。
