### ISSUE TITLE
顺序播放能否修改

### ISSUE THREAD

**Issue by yqh1996** [harry0703/MoneyPrinterTurbo#378]
我将ppt转变为图片，想要尝试顺序播放，但是播放时反着的。比如生成了10张ppt，播放顺序是10,9,8,7.尝试过修改图片生成时间和图片修改时间均没有成功

**Comment by harry0703** [comment]
你上传的顺序调整一下即可

**Comment by yqh1996** [comment]
已解决，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月23日(周四) 上午10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [harry0703/MoneyPrinterTurbo] 顺序播放能否修改 (Issue #378)




 
你上传的顺序调整一下即可
