### ISSUE TITLE
从网盘下载完解压后打不开

### ISSUE THREAD

**Issue by benkaggled** [harry0703/MoneyPrinterTurbo#379]
双击了update.bat执行更新
接着双击start.bat没有任何反应
config.toml里的APIs都部署好了
docker也下载了
就是打不开 点了start.bat没反应 
WHY？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by benkaggled** [comment]
访问Web界面也是显示该网页无法正常运作

**Comment by benkaggled** [comment]
@harry0703

**Comment by harry0703** [comment]
你打开 cmd 命令行，然后在命令行里面执行 start.bat，看看有什么报错
