### ISSUE TITLE
一些贡献的想法

### ISSUE THREAD

**Issue by alexdo83** [harry0703/MoneyPrinterTurbo#38]
一些贡献的想法:

1. 限制创建的字符数，...或添加创建视频的秒数选项/
2. 在可用文件夹中添加背景视频选择，...您可以在文件夹中随机选择或指定特定视频。
3. 新增手动输入故事功能
4. .....

**Comment by alexdo83** [comment]
是否可以创建像此演示视频这样的视频字幕？
Source: https://github.com/NisaarAgharia/AI-Shorts-Creator


https://github.com/harry0703/MoneyPrinterTurbo/assets/25850343/6f3eb5fa-49fd-4041-81f8-f0cad658658d

**Comment by harry0703** [comment]
@woshiyzq199611 已优化
增加了 `同时生成视频数量` 设置，可以设置 1-5个视频

更新代码试试，感谢建议
