### ISSUE TITLE
安装过程没有问题，运行时提示没有模块"movepy"，可是查看已经有了，什么问题？

### ISSUE THREAD

**Issue by shaweng** [harry0703/MoneyPrinterTurbo#385]
系统是windows11，安装过程没有提示任何问题，安装完后运行webui，提示如下：
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/6812660/9db6cfa5-f322-4222-84d4-086ee4668087)
conda list 又有
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/6812660/5a862545-50df-4422-a476-ee9ba038f5ff)

这会是什么问题？

**Comment by harry0703** [comment]
请确认一下，是否已经激活了虚拟环境，并且在虚拟环境里面执行的命令
