### ISSUE TITLE
无法生成字幕

### ISSUE THREAD

**Issue by michael7908** [harry0703/MoneyPrinterTurbo#397]
即便点选了生成字幕，最终的视频还是没有字幕。

**Comment by harry0703** [comment]
麻烦提供详细的信息，谢谢

**Comment by john911f** [comment]
我也遇到同样问题。不能生成中文字幕。可以生产英文字幕。
可能"Subtitle Font" (MicrosoftYaHeiBold.ttc 等等）只能生成英文。
要怎么添加中文"subtitle font"?
