### ISSUE TITLE
分享的微信群已经达到200人上限，只能有群成员邀请才可以进群，申请进群

### ISSUE THREAD

**Issue by zhangyiahsx** [harry0703/MoneyPrinterTurbo#398]
![Uploading 微信图片_20240603232250.png…]()
分享的微信群已经达到200人上限，只能有群成员邀请才可以进群，申请进群，本人微信号为zhangyiahsx

**Comment by harry0703** [comment]
https://github.com/harry0703/MoneyPrinterTurbo/raw/main/docs/wechat-group.jpg
