### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ifbulls2020** [harry0703/MoneyPrinterTurbo#400]
![微信图片_20240606155242](https://github.com/harry0703/MoneyPrinterTurbo/assets/58909700/95fdcf8e-5c24-40c5-b295-4a9e8af1ccee)

**Comment by ifbulls2020** [comment]
有空看下吧

**Comment by harry0703** [comment]
麻烦提供完整的日志信息，单单这个截图，很难判断是哪里的错误
