### ISSUE TITLE
解压到下一级文件夹打不开

### ISSUE THREAD

**Issue by kevinqingqinga** [harry0703/MoneyPrinterTurbo#402]
解压到根目录文件夹可以用，再往下一级文件夹，打开时就没有反应了，这个能解决吗？我是想放到我自己的portable文件夹里。谢谢

**Comment by harry0703** [comment]
文件夹名称中不能有 `中文`、`空格`、`特殊符号` 等

**Comment by kevinqingqinga** [comment]
明白了，谢谢回复！


________________________________
发件人: Harry ***@***.***>
发送时间: 星期五, 六月 7, 2024 1:44:06 下午
收件人: harry0703/MoneyPrinterTurbo ***@***.***>
抄送: kevinqingqinga ***@***.***>; Author ***@***.***>
主题: Re: [harry0703/MoneyPrinterTurbo] 解压到下一级文件夹打不开 (Issue #402)


文件夹名称中不能有 中文、空格、特殊符号 等

―
