### ISSUE TITLE
How to make better use of multiple cores for video merging?

### ISSUE THREAD

**Issue by UserItaly** [harry0703/MoneyPrinterTurbo#404]
I noticed it uses only 1-2% of my CPU (24 cores / 48 threads), and for a 1-minute video, it takes 30 minutes, with 27-28 minutes spent just on the last 2 stages where the videos are merged using ffmpeg.
How can I make it use more cores? Which part of the code do I need to modify?

Additionally, are there any settings that can be modified to speed it up further?

**Comment by harry0703** [comment]
On line 16 of the `app/services/task.py` code file, modify the `n_threads` parameter of `params`, for example, set `params.n_threads=10` to use more threads for parallel processing. 
This will increase CPU utilization.
