### ISSUE TITLE
关于本地素材使用

### ISSUE THREAD

**Issue by Mingzefei** [harry0703/MoneyPrinterTurbo#405]
Hi,
我对本地素材的使用有些疑问：
1. 使用本地素材时，多模态LLM是必须的吗？如果不是，需要自己手动打上文本标签吗？或者说，手动打标签能获得更好的效果，比如更好的相关性？
2. 我看到本地素材的大小（所有素材的整体大小，或许？）被限制在400MB以内。我很好奇为什么被限定在400MB？能不能被放开？我打算用它来处理一些本地的影视视频片段，总大小在几GB，甚至几十GB级别。

**Comment by harry0703** [comment]
1，大模型是需要的，因为要生成视频文案（此时标签不需要了，因为你用的是本地素材）
2，可以参考 https://docs.streamlit.io/knowledge-base/deploy/increase-file-uploader-limit-streamlit-cloud ，增加文件大小的限制
