### ISSUE TITLE
生成视频不知道成功与否，路径也不知道在哪，页面就直接跳回主页了

### ISSUE THREAD

**Issue by ylq545306** [harry0703/MoneyPrinterTurbo#411]
webui    | 2024-06-12 01:28:04 | INFO | "./app/services/video.py:40": combine_videos - max duration of audio: 158.16 seconds
webui    | 2024-06-12 01:28:04 | INFO | "./app/services/video.py:44": combine_videos - each clip will be maximum 3 seconds long
webui exited with code 137
webui    | 
webui    |   You can now view your Streamlit app in your browser.
webui    | 
webui    |   URL: http://127.0.0.1:8501
webui    | 
webui    | 
webui    |   A new version of Streamlit is available.

**Comment by harry0703** [comment]
这个看起来是程序被退出了，自动重启了
```
webui exited with code 137
```
可以看下系统是不是负载过高
