### ISSUE TITLE
存储API是否支持阿里云OSS存储？

### ISSUE THREAD

**Issue by superdreams** [harry0703/MoneyPrinterTurbo#412]
存储API是否支持阿里云OSS存储？
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/1644493/c66a37c4-ad61-49d4-83cf-8fa7db6153fe)

**Comment by superdreams** [comment]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/1644493/876aeb84-6a92-4632-9200-93a834bc0c16)

**Comment by harry0703** [comment]
暂时不支持，不过你可以自己扩展一下，比如容易 :)
