### ISSUE TITLE
docker: error pulling image configuration

### ISSUE THREAD

**Issue by micky-zh** [harry0703/MoneyPrinterTurbo#420]
docker run -p 3040:3040 missuo/freegpt35
Unable to find image 'missuo/freegpt35:latest' locally
latest: Pulling from missuo/freegpt35
4abcf2066143: Pulling fs layer 
62af34686b6b: Pulling fs layer 
87cba792d632: Pulling fs layer 
67eb332999b7: Pulling fs layer 
0f97c37d99cc: Pulling fs layer 
15506b6b84f0: Pulling fs layer 
7e609d2a64e6: Pulling fs layer 
27b30b2e2682: Pulling fs layer 
docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/1b/1b6fd3fa20f6e725abc03077a8d967ae73517e14208e2838fe2b467489a0a6e3/data?verify=1718938002-ZJn0dDRY4xQhtX6GC2MADzLqjzM%3D: dial tcp 104.244.46.5:443: i/o timeout.
See 'docker run --help'.

**Comment by harry0703** [comment]
网络问题，建议使用VPN连接
