### ISSUE TITLE
打包个docker，支持设置密码

### ISSUE THREAD

**Issue by lizhemin15** [harry0703/MoneyPrinterTurbo#43]
酱紫可以在服务器快速部署，后台生成了，不用自己电脑吭哧吭哧挂着跑了，谢谢大佬！

**Comment by harry0703** [comment]
确实在电脑上部署比较麻烦，这两天尽快弄下

**Comment by KevinZhang19870314** [comment]
添加了Dockerfile [146](https://github.com/harry0703/MoneyPrinterTurbo/pull/146)，麻烦review下。@harry0703

**Comment by KevinZhang19870314** [comment]
>支持设置密码

这个可以添加一下fastapi的auth功能，搞一个简单的通过key，后面可以使用oauth2。
