### ISSUE TITLE
执行webui.bat后报错

### ISSUE THREAD

**Issue by tianMaXiaoDi** [harry0703/MoneyPrinterTurbo#430]
执行webui.bat后出现TypeError: unsupported operand type(s) for |: 'type' and 'type'
![图片1](https://github.com/harry0703/MoneyPrinterTurbo/assets/130076117/e4b4ba0a-fe8b-47be-8b49-85944b228827)

**Comment by harry0703** [comment]
Python版本过低，最低要求 3.10 版本
