### ISSUE TITLE
这个必须科学上网吗？

### ISSUE THREAD

**Issue by theoldsong** [harry0703/MoneyPrinterTurbo#432]
第一次生成提示失败，failed to download videos, maybe the network is not available. if you are in China, please use a VPN.
后来开了科学上网，还是一样的错误

**Comment by harry0703** [comment]
网络不稳定，时不时无法访问，建议使用VPN

**Comment by easonton** [comment]
使用python request请求403，但是在服务器控制台执行curl能成功
