### ISSUE TITLE
2024-03-23 12:48:00.663 | ERROR    | app.services.task:start:117 - failed to download videos, maybe the network is not available. if you are in China, please use a VPN. 这个是为啥已经开了 vpn 了

### ISSUE THREAD

**Issue by Liu-Weidong-Void** [harry0703/MoneyPrinterTurbo#44]
2024-03-23 12:48:00.663 | ERROR    | app.services.task:start:117 - failed to download videos, maybe the network is not available. if you are in China, please use a VPN.

**Comment by congziqi77** [comment]
请问如何解决的？ 同样的问题开了vpn但是还是下载失败

**Comment by dayin0405** [comment]
我也是全局网络环境·换成全代理也不行

**Comment by harry0703** [comment]
一般是VPN软件的问题，另外注意下，设置全局代理后，需要重启服务

**Comment by 8824PPZ** [comment]
> 一般是VPN软件的问题，另外注意下，设置全局代理后，需要重启服务

挂了全局，再重启服务，依然还是有这个问题。。。

**Comment by zhrupdate** [comment]
llm_provider="g4f"，同样问题

**Comment by Dreyfi** [comment]
Please test if the [504](https://github.com/harry0703/MoneyPrinterTurbo/pull/504) solves the issue.
