### ISSUE TITLE
missuo/freegpt35 is not working anymore

### ISSUE THREAD

**Issue by victoriusnet** [harry0703/MoneyPrinterTurbo#445]
Hi,

In the English readme there is a free ChatGPT 3.5 API mentioned as missuo/freegpt35.

This package is not working anymore, the repo mentions https://github.com/missuo/FreeDuckDuckGo as an alternative but its not working neither.

Does anyone know a working solution for this?

Thank you!

**Comment by harry0703** [comment]
What about https://groq.com/ ?
