### ISSUE TITLE
受MoneyPrinterTurbo启发的一个node.js项目，感谢作者的开源精神

### ISSUE THREAD

**Issue by drawcall** [harry0703/MoneyPrinterTurbo#446]
[https://github.com/drawcall/FFAIVideo](https://github.com/drawcall/FFAIVideo) 一个使用行业流行AI LLM生成短视频的轻量nodejs项目。
该项目参考了[MoneyPrinterTurbo](https://github.com/harry0703/MoneyPrinterTurbo), [MoneyPrinter](https://github.com/FujiwaraChoki/MoneyPrinter), 和 [MsEdgeTTS](https://github.com/Migushthe2nd/MsEdgeTTS)等几个项目的源码，得到了很多启发和帮助。对这些开源项目的作者表示衷心的感谢。

**Comment by tuobay** [comment]
新项目与本项目的优势是啥？
