### ISSUE TITLE
代码bug

### ISSUE THREAD

**Issue by ChenRunPing** [harry0703/MoneyPrinterTurbo#451]
schema.py文件第98行，video_terms: Optional[str | list] = None  # 用于生成视频的关键词 报错，
改成 video_terms: Optional[str] = None  # 用于生成视频的关键词   才能运行成功

**Comment by harry0703** [comment]
```python
video_terms: Optional[str | list] = None
```
 这个写法在 Python 的类型注解中是有效的
但需要注意的是这种用法只在 **Python 3.10** 及以上的版本中才被支持。
