### ISSUE TITLE
关于代码的疑问

### ISSUE THREAD

**Issue by MonolithFoundation** [harry0703/MoneyPrinterTurbo#465]
您好，有一处地方我不是很懂，想请教作者。

<img width="719" alt="image" src="https://github.com/user-attachments/assets/ae216e77-17a7-4e9b-9488-983d97f7e31a">

zhe chu这处的代码，传入的subMaker始终是None，后面的调用未判断就直接调用了，这是为何啊？

**Comment by harry0703** [comment]
这里可能有bug，其他开发者修改了代码，我看下

**Comment by MonolithFoundation** [comment]
感谢，但是他好像也没有崩溃，很神奇啊

**Comment by harry0703** [comment]
已修复，感谢反馈👍🏻
