### ISSUE TITLE
Subtitles Improvement

### ISSUE THREAD

**Issue by RitoFan** [harry0703/MoneyPrinterTurbo#47]
How to stop the subtitles word from being cut in half instead of going to next line ?
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/16835494/f8dbb528-029c-4767-be2e-639dd807bfd8)****

**Comment by harry0703** [comment]
Thank you for the feedback. Could you send me your SRT subtitle file and MP3 audio file so I can try to optimize them?

**Comment by TomyDiNero** [comment]
Try srt_equalizer

**Comment by harry0703** [comment]
@RitoFan 
Thank you for the feedback.
I have optimized this issue. Please **update the code and try again**.
If there are any problems, feel free to provide feedback again.
