### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by enterprisium** [harry0703/MoneyPrinterTurbo#50]
how do i change the language? 
can you please tell how to deploy to huggingface space?
is there a way so that to application keep on running even when i am offline?

**Comment by harry0703** [comment]
do you mean change the UI display language? I will optimize this.
you can run as API mode, just `python main.py`, and thne access it use API.

**Comment by enterprisium** [comment]
Thank ammm an other question is there any plan to add direct upload to youtube support? actually i dont know much about api things.

well i've managed to change the language to english. i've also deployed it to huggingface space and made it working there but the problem is video successfully genrated but i couldnot find the video anywhere after genration is completed. maybe it needs to have a space to show genrated videos dor download genrated video or upload to youtube directly ?

**Comment by harry0703** [comment]
thank you, i will optimize it.
currently, the final videos are saved in ./storage/tasks/{task id}

**Comment by harry0703** [comment]
@enterprisium Now you can change the UI language to **English.**

<img width="665" alt="image" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/4928832/8ed664d7-9d0e-4094-85ba-c273b7bb3a9e">

**Comment by enterprisium** [comment]
thank you.
rest can you please give a little bit idea on how can i modefy the application so its automatically upload the video to youtube! i have deployed the app within hf.co it work well since there is not feature to veiw directly after the video is genrated i was thinking directly upload.
