### ISSUE TITLE
[Question] Can we set min-max duration for video generation ?

### ISSUE THREAD

**Issue by Greatz08** [harry0703/MoneyPrinterTurbo#519]
Asking this question because i dont understand chinese :-) so thought to ask about it here . 

One more doubt kind off my doubt is regarding its generation speed . I have RTX 4060 GPU with 8GB VRAM so will it be sufficient to generate small videos in your opinion ? 

[ Would have loved to ask these questions in discussion section but since this this project has no discussion section enabled so this is the only place where i could ask :-) ] 

Btw Thankyou very much for this great open source project

**Comment by yyhhyyyyyy** [comment]
Thank you for your questions and support!

Regarding duration settings:
Currently, it supports setting the maximum clip duration, but setting a minimum duration is not supported yet.

Regarding generation speed and hardware requirements:
Unless you are using locally deployed large language models (LLMs), video generation does not rely on GPU power. Therefore, the RTX 4060 GPU with 8GB VRAM will not have much impact in this case.
