### ISSUE TITLE
多語言的問題

### ISSUE THREAD

**Issue by Sara17176** [harry0703/MoneyPrinterTurbo#52]
我剛安裝好測試，關鍵詞寫入英文，Ai 的生成腳本一樣是 中文的，多語言好像還沒好

**Comment by harry0703** [comment]
感谢反馈
你使用的大模型LLM是哪个？
方便把llm那一块的日志贴出来看看么？

**Comment by Sara17176** [comment]
剛剛又在裝另外一台測試 沒問題了 兩次用的是 g4f 第二次裝用英文關鍵字就可以，但不太穩定，因為同樣主題有次跑出俄文。

新問題則是  字幕 才兩句字幕就沒在生成字幕了。

**Comment by harry0703** [comment]
g4f的稳定性是差一些，你是用的3.5还是4.0的，尽量有gpt 4.0的，对指令的遵循更好一些

> 新問題則是 字幕 才兩句字幕就沒在生成字幕了。
从日志里面，看生成的视频文案，是完整的么？

或者你把文案，script.json，subtitle.srt 和 final.mp4，这3个文件发出来，我定位下问题

**Comment by harry0703** [comment]
因为AI大模型不一定100%的按你输入的视频主题语言返回，因此增加了一个参数选择
这样如果你要指定语言，可以设置，这样更可控一些


![Snipaste_2024-03-26_17-00-36](https://github.com/harry0703/MoneyPrinterTurbo/assets/4928832/9ee8f6c3-6ec0-4f74-b041-68c356d20e52)
