### ISSUE TITLE
run main.py throw error

### ISSUE THREAD

**Issue by donghao85** [harry0703/MoneyPrinterTurbo#529]
hi:
My environment is macOS 14.4.1, with Python 3.10.15. All dependencies have been installed, and I confirm that the installation of moviepy is fine. However, run main.pyI am encountering the following error: ModuleNotFoundError: No module named 'moviepy.editor'. Did the package structure change starting from moviepy 2.0, and the code has not been updated in time?

**Comment by james-bond-007** [comment]
一样的问题，同问

**Comment by zhang-heng** [comment]
#528 11/20 moviepy 升级到2.0.0 ，请将这段代码改为 moviepy.*

**Comment by james-bond-007** [comment]
谢谢，成功解决问题！

**Comment by irfnrdh** [comment]
pip uninstall moviepy
pip install moviepy==1.0.3

**Comment by yyhhyyyyyy** [comment]
Please pull the latest code to access the fix.
