### ISSUE TITLE
执行webUI.sh 启动生成视频卡住了

### ISSUE THREAD

**Issue by TzyTman** [harry0703/MoneyPrinterTurbo#53]
<img width="1931" alt="截屏2024-03-25 15 20 02" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/3644883/637e8f38-0a4c-42fd-aa96-15bfa2d3fde2">
<img width="1842" alt="截屏2024-03-25 15 20 11" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/3644883/5e2863c3-f009-47ef-9620-4b78509d0b58">

这是我配置文件的参数如图：
![WechatIMG377](https://github.com/harry0703/MoneyPrinterTurbo/assets/3644883/3ebe2b1e-0bae-4969-ba6e-d5aa9fa59240)

等了差不多有半个多小时吧。没反应 也没有任何输出？ 是什么情况？ 我使用的是g4f

**Comment by harry0703** [comment]
看日志，像是下载卡在了，比较慢的缘故。
我优化下，加个超时

**Comment by TzyTman** [comment]
博主回复很及时谢谢！ 我使用OpenAI chatGPT4 的Key  openai_base_url 这个参数是可选的吧？ 我没填写也可以正常运行 只是下载视频卡住了。

**Comment by TzyTman** [comment]
![WeChat20abaa90d1b95da825961418de1d3afa](https://github.com/harry0703/MoneyPrinterTurbo/assets/3644883/5101942c-7a2d-4e61-ae72-6440784d1d14)
openai_base_url  这个参数 我填写的是：openai_base_url="https://api.openai.com/v1/completions" 但是运行的时候报 找不到
completions？

**Comment by TzyTman** [comment]
<img width="699" alt="截屏2024-03-25 16 20 23" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/3644883/a1b01bbb-68f4-4e77-bf18-35e93d5fed68">
问题已解决 跟网络相关 建议使用vpn 进行视频下载

**Comment by harry0703** [comment]
> openai_base_url

openai_base_url 这个是可选的，相当于代理，可以不设置
