### ISSUE TITLE
ModuleNotFoundError: No module named 'moviepy.editor'

### ISSUE THREAD

**Issue by jalesg1** [harry0703/MoneyPrinterTurbo#535]
ModuleNotFoundError: No module named 'moviepy.editor'
Traceback:

File "C:\Users\sandz\anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "C:\Users\sandz\OneDrive\Desktop\MoneyPrinterTurbo\webui\Main.py", line 37, in <module>
    from app.services import task as tm
File "C:\Users\sandz\OneDrive\Desktop\MoneyPrinterTurbo\app\services\task.py", line 12, in <module>
    from app.services import llm, material, subtitle, video, voice
File "C:\Users\sandz\OneDrive\Desktop\MoneyPrinterTurbo\app\services\video.py", line 7, in <module>
    from moviepy.editor import *

**Comment by Dipesh79** [comment]
"""Imports everything that you need from the MoviePy submodules so that every thing
can be directly imported with ``from moviepy import *``.
"""

It is started in __init__.py file of this package. So you can import using 
```from moviepy import *``` import statement.

**Comment by zsf513** [comment]
#529 , execute the command: 
pip uninstall moviepy
pip install moviepy==1.0.3

**Comment by Yellodas** [comment]
Change the sixth line of the file app/services/video.py to 'from moviepy import *'.

**Comment by mrayushmehrotra** [comment]
I'm getting the same error, it was working in my Ubuntu 24(version) but not working in Pop Os ( i don't know why this happens?)

**Comment by mrayushmehrotra** [comment]
![Screenshot from 2024-11-30 11-06-51](https://github.com/user-attachments/assets/f4440c18-995b-4c1d-a0ba-9413bdfa76dd)



so guys after the November release of moviepy they removed editor module

 to fix this error temporarily you can downgrade to Moviepy 1.0.3

**Comment by youyouge** [comment]
> I have the same problem

pip uninstall moviepy
pip install moviepy==1.0.3

**Comment by yyhhyyyyyy** [comment]
Please pull the latest code to access the fix.

**Comment by danielramrain** [comment]
> ![Screenshot from 2024-11-30 11-06-51](https://private-user-images.githubusercontent.com/110099419/391214658-f4440c18-995b-4c1d-a0ba-9413bdfa76dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODg5ODAsIm5iZiI6MTczMzY4ODY4MCwicGF0aCI6Ii8xMTAwOTk0MTkvMzkxMjE0NjU4LWY0NDQwYzE4LTk5NWItNGMxZC1hMGJhLTk0MTNiZGZhNzZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQyMDExMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDM0YzZjMmQ4ZWEwZTA4YjY5MzllMDBiNDg2NjJiNGVmZjczNDExODBjN2ZlMTkwOTUwOWMwNjFmZDkzMjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PckAeYl78OUHofyLhuI8oPtSidfNlkDLFUUWby2DSPk)
> 
> so guys after the November release of moviepy they removed editor module, they have changed some dir's
> 
> to fix this error temporarily you can downgrade to Moviepy 1.0.3

Бро! Спасибо тебе огромное за инфу. Ты очень выручил

**Comment by LukeLIN-web** [comment]
You could `from moviepy import VideoFileClip`

**Comment by AmirhoseynLali** [comment]
i had same problem for using  : 
from moviepy.editor import VideoFileClip, concatenate_videoclips
than i removed the editor and :  from moviepy import VideoFileClip, concatenate_videoclips  runs very well.

**Comment by JohnProjetos** [comment]
> ![Captura de tela de 2024-11-30 11-06-51](https://private-user-images.githubusercontent.com/110099419/391214658-f4440c18-995b-4c1d-a0ba-9413bdfa76dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5MjA3MTQsIm5iZiI6MTczNTkyMDQxNCwicGF0aCI6Ii8xMTAwOTk0MTkvMzkxMjE0NjU4LWY0NDQwYzE4LTk5NWItNGMxZC1hMGJhLTk0MTNiZGZhNzZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QxNjA2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDVkNjAyNmY2OTkzMTQwNjNhODdmMmZmMmIzNDVhOTg2OTEzZTJiNTNkNjAyNmNjMTViY2NmYzViMWQxNWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.y1MWQQU5Ip21AFe8phJtoNirIJM7o-NT0aAGSjyCLgU)
> 
> então pessoal, depois do lançamento do moviepy em novembro, eles removeram o módulo do editor e mudaram alguns diretórios
> 
> para corrigir esse erro temporariamente você pode fazer o downgrade para o Moviepy 1.0.3

Thank you so much, you saved me!

**Comment by raheemakhter48** [comment]
pip install moviepy==1.0.3

**Comment by zhangyic02** [comment]
> pip install moviepy==1.0.3

this worked for me. Also "from moviepy import *" worked too

**Comment by akaran-109** [comment]
Solution 1 - Use Direct Import
For moviepy version 2.x and above, use:

**Comment by nepia-infinity** [comment]
@akaran-109 

from moviepy.video.io.VideoFileClip import VideoFileClip

最高です！！
動きましたッ！！ありがとう！！

**Comment by Accorinrin** [comment]
> [@akaran-109](https://github.com/akaran-109)
> 
> from moviepy.video.io.VideoFileClip import VideoFileClip
> 
> 最高です！！ 動きましたッ！！ありがとう！！

thanks a lot!! this worked :D

**Comment by duyanfang123** [comment]
> > I have the same problem
> 
> pip uninstall moviepy pip install moviepy==1.0.3

I must sign in to agree once

**Comment by Shaurya-Grover** [comment]
@jalesg1  the error you are facing can be easily installed by downloading the package     ` pip install moviepy==1.0.3`   this helps in completing your dependency.
