### ISSUE TITLE
NotFoundError: Error code: 404 Invalid URL (POST /v1/chat/completions/chat/completions

### ISSUE THREAD

**Issue by WebKing2024** [harry0703/MoneyPrinterTurbo#57]
NotFoundError: Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1/chat/completions/chat/completions)', 'type': 'invalid_request_error', 'param': None, 'code': None}}

When I finished deploying the execution program, the above error was reported...I found this in the config file:
openai_base_url = "https://api.openai.com/v1/chat/completions"
openai_model_name = "gpt-4-turbo-preview"

Why are URLs duplicated?How can I fix this problem, thanks man...

**Comment by harry0703** [comment]
You only need to leave the openai_base_url empty, no need to set it unless you want to use your own proxy.

**Comment by harry0703** [comment]
> APITimeoutError: Request timed out.

It seems that your network is unable to connect to OPENAI's servers. Please ensure your network is working smoothly, or consider using a **proxy**.

**Comment by WebKing2024** [comment]
As a beginner, thank you very much for your guidance. I am sending you a star to express my gratitude.
