### ISSUE TITLE
moov atom not found

### ISSUE THREAD

**Issue by mrfuturman** [harry0703/MoneyPrinterTurbo#61]
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001f5f514f340] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001f5f514f340] moov atom not found
[in#0 @ 000001f5f514ef40] Error opening input: Invalid data found when processing input
Error opening input file D:\MoneyPrinterTurbo\storage\tasks\a99df9d7-ad0c-4398-822b-e69735a772c4/vid-1711372631489.mp4.
Error opening input files: Invalid data found when processing input
请问这个怎么解决

**Comment by harry0703** [comment]
可能是这个视频没有下载成功（比如中途网络中断了），暂时重试一下
我下个版本优化下这个问题

**Comment by AemonChan** [comment]
谢谢大佬，我再问一个问题， 我是普通注册的chatgpt（没花钱买plus）生成的api，然后这个地方openai_model_name = "gpt-3.5-turbo"，填哪个类型，我试了好几个都不行

**Comment by harry0703** [comment]
你需要看下你后台的模型列表：https://platform.openai.com/account/limits
只能填写被授权的

![Snipaste_2024-03-26_15-40-18](https://github.com/harry0703/MoneyPrinterTurbo/assets/4928832/b9eb79a3-b002-442b-97fa-501a197e0665)
