### ISSUE TITLE
可以用自己的素材吗

### ISSUE THREAD

**Issue by SHITIANYU-hue** [harry0703/MoneyPrinterTurbo#62]
请问一下可以加载自己的素材吗？不用您提供的

**Comment by harry0703** [comment]
好主意，我优化一下

**Comment by paynepang** [comment]
> 好主意，我优化一下

可以优化下，视频不是从pexels下载拼接的，而是直接大模型语言生成的一段视频。

**Comment by 7mue3ttT** [comment]
视频的背景的几种情况:
1. 单张图片固定不动;
2. 单个视频循环播放;
3. 图片 + 视频组合后的循环播放;
1和2应该是比较多用的情况.
感谢付出时间. @harry0703

**Comment by harry0703** [comment]
@7mue3ttT 单张图片固定不动
① 是从头到尾都是一张图片固定不动？
② 还是每个图片只是在片段内固定不动？比如视频时长 10 秒，每2秒一张图片，2秒内，该图片固定不动？

另外请教下，单张图片固定不动 和 单个视频循环播放，一般是在什么场景下使用较多？谢谢

**Comment by baicai** [comment]
> @7mue3ttT 单张图片固定不动 ① 是从头到尾都是一张图片固定不动？ ② 还是每个图片只是在片段内固定不动？比如视频时长 10 秒，每2秒一张图片，2秒内，该图片固定不动？
> 
> 另外请教下，单张图片固定不动 和 单个视频循环播放，一般是在什么场景下使用较多？谢谢

我第一次使用就遇到了这个情况，我选择了同时生成5个视频，然后每个视频都长一样，文件大小也都一样，而且总是一段一个穿红色衣服的老太婆翻手机的视频反复播放，而且这段视频跟我的主题没有半分钱关系。

**Comment by 7mue3ttT** [comment]
> @7mue3ttT 单张图片固定不动 ① 是从头到尾都是一张图片固定不动？ ② 还是每个图片只是在片段内固定不动？比如视频时长 10 秒，每2秒一张图片，2秒内，该图片固定不动？
> 
> 另外请教下，单张图片固定不动 和 单个视频循环播放，一般是在什么场景下使用较多？谢谢

1. 从头到尾一直固定不动, 属于基本需求, 适合“虽然是视频, 本质是听”的场景; 这里应该支持上传自己的素材;
2. 是1 的升级,  有更好, 可以作为 1 的升级版本;
要支持自己上传素材的原因之一: 如果想生成长视频, 目前的自动下载模式,会导致 ffmpeg出现素材数量过多的错误,我遇到过这个错误, 支持用户自己上传时, 规定一个上限, 可以解决这个问题.

感谢两位回复.
@harry0703 @baicai

**Comment by 7mue3ttT** [comment]
视频的时长, 现在似乎有些歧义, web页面说最长6秒,实际上可以生成 远不止6秒的视频;
我输入很长一段文案, 想生成长视频, 又遇到 ffmpeg 加载素材过多的错误;

有一个很直接的场景: 
支持用户上传一张(或多张)图片, 把ffmpeg的错误解决, 根据音频的时长决定视频的时长; 就已经是一款不错的视频工具了. 虽然市面上有很多可以满足这个场景的GUI工具, 但是咱们提供了接口, 非常适合有一定开发能力的团队.
@harry0703 @baicai

**Comment by harry0703** [comment]
感谢反馈，我们尽快优化~

**Comment by focus883** [comment]
> 请问一下可以加载自己的素材吗？不用您提供的

希望可以搜索自己网盘的素材，实现使用自己的素材。默认的素材网都是国外的，匹配度不高

**Comment by harry0703** [comment]
1.1.5 版本已经加入本地素材支持了，一些效果还在优化中
