### ISSUE TITLE
下载视频素材问题

### ISSUE THREAD

**Issue by mentos523** [harry0703/MoneyPrinterTurbo#64]
我现在问题是开了VPN，到视频素材下载就报错了

`2024-03-26 11:11:57 | INFO | "./app\services\material.py:123": download_videos - downloading video: https://player.vimeo.com/progressive_redirect/playback/438464700/rendition/1080p/file.mp4?loc=external&oauth2_token_id=17***641&signature=65648d4da******432191ef9f0077b01b240bde8132330c1c4290e140`

`2024-03-26 11:11:57 | ERROR | "./app\services\material.py:132": download_videos - failed to download video: <app.models.schema.MaterialInfo object at 0x000001600CD26290>, HTTPSConnectionPool(host='player.vimeo.com', port=443): Max retries exceeded with url: /progressive_redirect/playback/438464700/rendition/1080p/file.mp4?loc=external&oauth2_token_id=17***641&signature=65648d4da*******432191ef9f0077b01b240bde8132330c1c4290e140 (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))))`

这个素材手动在浏览器是可以下载的。关了VPN Tun模式，报没有开启VPN。

**Comment by TzyTman** [comment]
那你找把梯子
