### ISSUE TITLE
网页多端访问的时候，某些文件会冲突，目前不支持并行多个运行是么

### ISSUE THREAD

**Issue by HuangXihuang** [harry0703/MoneyPrinterTurbo#74]
开启了两个页面，同时跑两个任务，其中一个成功，另外一个提示：

PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'final-1.mp4.tempTEMP_MPY_wvf_snd.mp3'
Traceback:

目前不支持并行多个同时运行是么？

**Comment by HuangXihuang** [comment]
过程文件的命名不同task可能需要区分开，发现因为使用了同一个文件名，A task会把内容写入 B task的文件内

**Comment by HuangXihuang** [comment]
有小伙伴碰到类似情况否？

**Comment by harry0703** [comment]
感谢反馈，我定位下原因

**Comment by harry0703** [comment]
已修复，麻烦更新代码再试试

**Comment by ashq3** [comment]
![Image](https://github.com/user-attachments/assets/04280184-83d7-44fe-a0e2-fde2eeafdc04)
另一个程序正在使用此文件，进程无法访问。: 'temp-clip-5TEMP_MPY_wvf_snd.mp3'    这个mp3文件也会有这个问题
