### ISSUE TITLE
Pillow升级到10之后图片处理会出现异常

### ISSUE THREAD

**Issue by fighter2011** [harry0703/MoneyPrinterTurbo#75]
Pillow10之后移除了Image.ANTIALIAS，我看原作者是9.5.0

`MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/fx/resize.py", line 37, in resizer
    resized_pil = pilim.resize(newsize[::-1], Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
`

**Comment by smaltum** [comment]
@fighter2011 用 8.4.0 试试

**Comment by fighter2011** [comment]
> @fighter2011 用 8.4.0 试试

ok
