### ISSUE TITLE
linux生成视频时报错 local_files_only=false 问题

### ISSUE THREAD

**Issue by wz609658018** [harry0703/MoneyPrinterTurbo#84]
![微信截图_20240328101352](https://github.com/harry0703/MoneyPrinterTurbo/assets/42161544/182555f2-5b44-43b5-85ec-a9e044e1d14e)

**Comment by wz609658018** [comment]
强行修改 conda根目录  ./lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py 中的 local_files_only 默认为True， 问题修复

**Comment by harry0703** [comment]
该问题优化了，默认设置了 local_files_only=True
可以不用修改 huggingface 的源码了

**Comment by wz609658018** [comment]
> 该问题优化了，默认设置了 local_files_only=True 可以不用修改 huggingface 的源码了

收到

**Comment by xiaofeige** [comment]
问题并没有解决哇，现在修改 /lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py 中的 local_files_only  都没用了，一直提示 相同的错误

**Comment by harry0703** [comment]
抱歉，我还原了代码，这个地方是有点问题，我需要深入定位一下
你还是先改 huggingface 的源码解决吧

**Comment by ivanberry** [comment]
这个后续有什么好的解决办法吗？

**Comment by iqilu2012** [comment]
使用edge的时候没有问题。这个方法。但是用wishp那个。把所有的都改的true也不行

**Comment by harry0703** [comment]
> 使用edge的时候没有问题。这个方法。但是用wishp那个。把所有的都改的true也不行

你的网络是正常的么？能访问huggingface么？
不光是浏览器可以访问（需要全局流量能访问）

**Comment by harry0703** [comment]
参见：https://github.com/harry0703/MoneyPrinterTurbo/issues/166

**Comment by a736875071** [comment]
这个问题还是存在,没有修复

**Comment by harry0703** [comment]
@a736875071  解决办法就是设置环境变量，因为无法从huggingface下载模型
```
export HF_ENDPOINT=https://hf-mirror.com
```

或者手动下载模型：https://github.com/harry0703/MoneyPrinterTurbo?tab=readme-ov-file#%E5%AD%97%E5%B9%95%E7%94%9F%E6%88%90-
