### ISSUE TITLE
Streamlit在固定时刻断开

### ISSUE THREAD

**Issue by kantegger** [harry0703/MoneyPrinterTurbo#85]
每次生成到 writing to temp file 这个步骤时，Streamlit就会断开显示CONNECTING。如下：
2024-03-28 10:58:23.700 | INFO     | app.services.video:generate_video:224 - writing to temp file: .\storage\tasks\d67476ee-e289-4ee9-aea4-618f44f435e9\final-1.mp4.temp.mp4

重新部署代码后也是一样的。麻烦帮我看看，谢谢。

**Comment by kantegger** [comment]
补充一下，把生成字幕关掉可以输出完成。

**Comment by harry0703** [comment]
可能是浏览器的问题，你可以尝试换个浏览器试试
或者打开浏览器的开发人员工具，看看 控制台 是否有报错？

![Snipaste_2024-03-28_11-39-06](https://github.com/harry0703/MoneyPrinterTurbo/assets/4928832/3af73e17-9079-4677-8e53-9cc6843386b4)

<img width="568" alt="image" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/4928832/be234654-31d9-44ff-8c5b-2d8adf4ffd10">

**Comment by zhuangzhuang3** [comment]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/164452484/213b58d6-35c2-4594-bf09-3a40a2d7be24)
我也遇到了，但是跟你的报错不一样

**Comment by harry0703** [comment]
@W01fh4cker 你这个是最后生成视频的时候，命令行里面的服务，直接退出了么？

**Comment by W01fh4cker** [comment]
> @W01fh4cker 你这个是最后生成视频的时候，命令行里面的服务，直接退出了么？

是的，`writing video`这一步直接退出了。

**Comment by harry0703** [comment]
@W01fh4cker 

1，可以检查下 FFMPEG 的版本看看，不确定是不是版本过低，编码的时候有异常，比如下面是我的ffmpeg版本
```
➜  ~ ffmpeg
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.1.1_4 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenvino --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
```

2，是否有安装一些安全/优化软件？因为编码的时候，会大量占用CPU，有些软件会直接把高CPU的进程，给杀掉

**Comment by zhuangzhuang3** [comment]
> ```
> 12076 killed
> ```
> 
> 这个看起来，好像是资源消耗过高，被系统杀掉了 在处理的时候，你看看系统负载是不是比较高？
是的。换了个多核的CPU就好了

**Comment by W01fh4cker** [comment]
> @W01fh4cker
> 
> 1，可以检查下 FFMPEG 的版本看看，不确定是不是版本过低，编码的时候有异常，比如下面是我的ffmpeg版本
> 
> ```
> ➜  ~ ffmpeg
> ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
>   built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)
>   configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.1.1_4 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenvino --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
>   libavutil      58. 29.100 / 58. 29.100
>   libavcodec     60. 31.102 / 60. 31.102
>   libavformat    60. 16.100 / 60. 16.100
>   libavdevice    60.  3.100 / 60.  3.100
>   libavfilter     9. 12.100 /  9. 12.100
>   libswscale      7.  5.100 /  7.  5.100
>   libswresample   4. 12.100 /  4. 12.100
>   libpostproc    57.  3.100 / 57.  3.100
> ```
> 
> 2，是否有安装一些安全/优化软件？因为编码的时候，会大量占用CPU，有些软件会直接把高CPU的进程，给杀掉

1. 应该和版本没关系，我升级到了`6.1.1`也没用，并且之前调用是没问题的后面调用出现了问题，如下图：
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/101872898/e643bbc6-0966-4030-a271-878108d95ab1)
2. 我是`win10`，运行过程中`CPU`占用没有超过`62%`。

**Comment by HeathKang** [comment]
Same here, I workaround like this to fix the issue (**disable the progress bar**):
```
final_clip.write_videofile(combined_video_path, threads=threads, logger=None)
```
https://github.com/harry0703/MoneyPrinterTurbo/blob/7fb1a95a82c3795df56ac0452320be3c281e9ee4/app/services/video.py#L95

please reference this thread which is a known issue in `moviepy` https://github.com/Zulko/moviepy/issues/645
