### ISSUE TITLE
运行报错：AttributeError: 'str' object has no attribute 'choices'

### ISSUE THREAD

**Issue by kid9547** [harry0703/MoneyPrinterTurbo#87]
Traceback如下：
File "C:\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "E:\MoneyPrinterTurbo\webui\Main.py", line 264, in <module>
    tm.start(task_id=task_id, params=cfg)
File "E:\MoneyPrinterTurbo\app\services\task.py", line 51, in start
    video_script = llm.generate_script(video_subject=video_subject, language=params.video_language,
File "E:\MoneyPrinterTurbo\app\services\llm.py", line 118, in generate_script
    response = _generate_response(prompt=prompt)
File "E:\MoneyPrinterTurbo\app\services\llm.py", line 86, in _generate_response
    content = response.choices[0].message.content

根据报错信息看起来问题出在_generate_response函数返回的对象类型不是预期的类型。报错信息显示'str' object has no attribute 'choices'，意味着response是一个字符串而不是期望的对象，因此无法通过choices属性来访问内容。但是我不知怎么解决0.0

**Comment by GodJones** [comment]
## macOS 14.4.1 在运行的时候提示报错
### 报错信息如下
`video subject: 生活如此美好
- number of paragraphs: 1
2024-03-28 16:15:58 | INFO | "./app/services/llm.py:15": _generate_response - llm provider: openai
2024-03-28 16:15:59.201 Uncaught app exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/Users/mac/AiCreate/MoneyPrinterTurbo/webui/Main.py", line 117, in <module>
    script = llm.generate_script(video_subject=cfg.video_subject, language=cfg.video_language)
  File "/Users/mac/AiCreate/MoneyPrinterTurbo/app/services/llm.py", line 105, in generate_script
    response = _generate_response(prompt=prompt)
  File "/Users/mac/AiCreate/MoneyPrinterTurbo/app/services/llm.py", line 73, in _generate_response
    content = response.choices[0].message.content
AttributeError: 'str' object has no attribute 'choices'`
### 希望解决一下，谢谢。

**Comment by harry0703** [comment]
这个问题是由于OPENAI没有返回正确的回复，**大概率是网络原因导致**的。
使用`VPN`，或者找个代理，设置 `openai_base_url` ，应该就可以解决了

**Comment by kid9547** [comment]
> 这个问题是由于OPENAI没有返回正确的回复，**大概率是网络原因导致**的。 使用`VPN`，或者找个代理，设置 `openai_base_url` ，应该就可以解决了

我确信我设置好了openai_base_url，并且也用chatbox等软件测试了api和转发地址的有效性，但是还是同样的报错：
AttributeError: 'str' object has no attribute 'choices'
Traceback:
File "C:\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "E:\MoneyPrinterTurbo\webui\Main.py", line 264, in <module>
    tm.start(task_id=task_id, params=cfg)
File "E:\MoneyPrinterTurbo\app\services\task.py", line 51, in start
    video_script = llm.generate_script(video_subject=video_subject, language=params.video_language,
File "E:\MoneyPrinterTurbo\app\services\llm.py", line 118, in generate_script
    response = _generate_response(prompt=prompt)
File "E:\MoneyPrinterTurbo\app\services\llm.py", line 86, in _generate_response
    content = response.choices[0].message.content

**Comment by kid9547** [comment]
设置如下，有些部分我用`*`代替了，其他没有改变 
########## OpenAI API Key
    # Visit https://openai.com/api/ for details on obtaining an API key.
    openai_api_key = "sk-b2h9IIfzAb5JWfNp*****************************************"
    openai_base_url = "https://api.********.cn" # no need to set it unless you want to use your own proxy
    openai_model_name = "gpt-4-turbo-preview"

**Comment by harry0703** [comment]
`openai_base_url`  的配置看起来是错的？
一般是类似这样 
```toml
openai_base_url = "http://xxx.xxxx.com/v1/"
```

**Comment by dx1995** [comment]
我也发生了这个问题，我配置的转发地址是正确可用的，但在此项目无法使用。

**Comment by harry0703** [comment]
@dx1995 你可以使用 `curl` 直接用的 **转发地址** 测试看看能不能用
后面计划提供一个公共的proxy地址出来
国内好多用户，卡在了这个环节

**Comment by dx1995** [comment]
(MoneyPrinterTurbo) C:\Users\HASEE\MoneyPrinterTurbo>curl https://api.uu.ci
<!doctype html><html lang="zh-cn"><head><meta charset="utf-8"/><link href='https://img.aiwl.cc/images/2024/03/04/icon.png' rel='icon'><meta content="width=device-width,initial-scale=1" name="viewport"/><meta content="#ffffff" name="theme-color"/><meta content="UUAPI免费接口，真正的免费GPT接口" name="description"/><title>UU免费接口</title><script defer="defer" src="/static/js/main.c17d6dd7.js"></script></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><div id="globalModalContainer"></div><script>(function(){if (!document.body) return;var js = "window['__CF$cv$params']={r:'86c85ef51d9c945c',t:'MTcxMTgwNDU1Mi41MzcwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body></html>
(MoneyPrinterTurbo) C:\Users\HASEE\MoneyPrinterTurbo>

**Comment by kid9547** [comment]
> `openai_base_url` 的配置看起来是错的？ 一般是类似这样
> 
> ```toml
> openai_base_url = "http://xxx.xxxx.com/v1/"
> ```

感谢，的确是我的`openai_base_url`写错了，少写了`/v1`  0.0
