### ISSUE TITLE
[BUG] 使用繁體中文時的問題

### ISSUE THREAD

**Issue by avijitbatra939** [harry0703/MoneyPrinterTurbo#9]
使用  edge-tts 裡面的 zh-TW 聲音時會出現無法將最後一段的字幕結合在影片中
同時也會產生 wrap_text 的警告

`2024-03-12 16:10:00 | WARNING | "./app/services/video.py:108": wrap_text - wrapping text, max_width: 980, text_width: 1243, text: USB設計的初衷是為了簡化電腦週邊設備的連接`

**Comment by harry0703** [comment]
已优化，可以更新代码后再试试
