### ISSUE TITLE
这个问题怎么解决？

### ISSUE THREAD

**Issue by yll2791** [harry0703/MoneyPrinterTurbo#90]
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by harry0703** [comment]
这个看起来是环境问题，你可以参考一下这个
https://stackoverflow.com/questions/64209238/error-15-initializing-libiomp5md-dll-but-found-libiomp5md-dll-already-initial

**Comment by lylgxy888** [comment]
可能是因为安装了多个与OpenMP相关的库，相关的每个库都安装了libiomp5md.dll文件，我的解决方法是将ctranslate2库所在目录下的libiomp5md.dll修改了文件名，就可以正常运行了
