### ISSUE TITLE
生成16:9比例视频时候素材被莫名拉升

### ISSUE THREAD

**Issue by SarcomTDG** [harry0703/MoneyPrinterTurbo#91]
我在生成16:9比例视频时
视频原本正常16:9但是合成后出现被拉升状况
![微信截图_20240328154923](https://github.com/harry0703/MoneyPrinterTurbo/assets/95288331/a1b4cd7d-7d1e-45c2-b4e3-f2a1325552b3)
出现拉升的视频源文件
https://github.com/harry0703/MoneyPrinterTurbo/assets/95288331/46f60350-1ff1-42d2-8e93-628340753f55
合成后的视频
https://github.com/harry0703/MoneyPrinterTurbo/assets/95288331/73a66a19-c822-40df-9107-d465dc1ccc76

**Comment by harry0703** [comment]
收到，我定位下原因
如果可能的话，把该 task id 的文件夹压缩一下，上传到这里，有助于我更好的定位和优化
感谢您的反馈

**Comment by SarcomTDG** [comment]
链接: https://pan.baidu.com/s/1Xh41UauxhAoMs82AstHaFw 提取码: prg8 
链接: https://pan.baidu.com/s/1nwEcqA8YJk8XNVjtiDdqpw 提取码: u5dc 
我是通过接口调用 调用json:{
  "video_subject": "啤酒饮料加蹦迪",
  "video_script": "",
  "video_terms": "",
  "video_aspect": "16:9",
  "video_concat_mode": "random",
  "video_clip_duration": 5,
  "video_count": 1,
  "video_language": "",
  "voice_name": "female-zh-CN-XiaoxiaoNeural",
  "bgm_type": "random",
  "bgm_file": "",
  "bgm_volume": 0.2,
  "subtitle_enabled": true,
  "subtitle_position": "bottom",
  "font_name": "STHeitiMedium.ttc",
  "text_fore_color": "#FFFFFF",
  "text_background_color": "transparent",
  "font_size": 60,
  "stroke_color": "#000000",
  "stroke_width": 1.5,
  "n_threads": 2,
  "paragraph_number": 1
}

**Comment by SarcomTDG** [comment]
> 收到，我定位下原因 如果可能的话，把该 task id 的文件夹压缩一下，上传到这里，有助于我更好的定位和优化 感谢您的反馈

链接: https://pan.baidu.com/s/1Xh41UauxhAoMs82AstHaFw 提取码: prg8 
链接: https://pan.baidu.com/s/1nwEcqA8YJk8XNVjtiDdqpw 提取码: u5dc 
我是通过接口调用 调用json:{
  "video_subject": "啤酒饮料加蹦迪",
  "video_script": "",
  "video_terms": "",
  "video_aspect": "16:9",
  "video_concat_mode": "random",
  "video_clip_duration": 5,
  "video_count": 1,
  "video_language": "",
  "voice_name": "female-zh-CN-XiaoxiaoNeural",
  "bgm_type": "random",
  "bgm_file": "",
  "bgm_volume": 0.2,
  "subtitle_enabled": true,
  "subtitle_position": "bottom",
  "font_name": "STHeitiMedium.ttc",
  "text_fore_color": "#FFFFFF",
  "text_background_color": "transparent",
  "font_size": 60,
  "stroke_color": "#000000",
  "stroke_width": 1.5,
  "n_threads": 2,
  "paragraph_number": 1
}

**Comment by harry0703** [comment]
已经修复了，可以更新代码后，再试下
有问题欢迎反馈
谢谢~
