### ISSUE TITLE
API生成视频后获取不到下载链接

### ISSUE THREAD

**Issue by qq1574829575** [harry0703/MoneyPrinterTurbo#95]
通过api/v1/tasks接口输入正确的task_id获取不到生成的视频
视频保存在storage/tasks目录下
api/v1/tasks目录不存在

**Comment by harry0703** [comment]
抱歉
该接口还没有开发完成
会尽快完善上去

**Comment by qq1574829575** [comment]
噢噢，非常感谢，我以为是我自己的问题，研究了一下午

**Comment by KevinZhang19870314** [comment]
> 噢噢，非常感谢，我以为是我自己的问题，研究了一下午

这个应该好了，@qq1574829575 试一下没问题可以关闭了
