### ISSUE TITLE
是否可以将应用程序界面转换为双语？(English)

### ISSUE THREAD

**Issue by alexdo83** [harry0703/MoneyPrinterTurbo#97]
是否可以将应用程序界面转换为双语？
我不懂中文，请改成英文界面选择？

![webui](https://github.com/harry0703/MoneyPrinterTurbo/assets/25850343/6a957590-6aa7-4905-9118-71e98e5eb4d7)

**Comment by smaltum** [comment]
@alexdo83 You can use the edge browser to open the operation page after local deployment, and then right-click the edge browser to use the translation。

**Comment by harry0703** [comment]
Thank you for the feedback. We are currently translating it into English and will commit the code shortly.

**Comment by harry0703** [comment]
@alexdo83 Now you  can change the UI language to English

<img width="549" alt="image" src="https://github.com/harry0703/MoneyPrinterTurbo/assets/4928832/e91fb929-828d-4b1e-906a-4a90fed37b08">
