### ISSUE TITLE
Insanely Fast Whisper

### ISSUE THREAD

**Issue by slavakurilyak** [harry0703/MoneyPrinterTurbo#98]
Have you tested [insanely-fast-whisper](https://github.com/Vaibhavs10/insanely-fast-whisper) by @Vaibhavs10?

It would be great to compare it to [faster-whisper](https://github.com/SYSTRAN/faster-whisper) by @SYSTRAN

**Comment by harry0703** [comment]
Thank you for the feedback. 
I will test it, and if it works better, it will also be integrated into the project as a solution.
