### ISSUE TITLE
字幕生成一半

### ISSUE THREAD

**Issue by duffercn** [harry0703/MoneyPrinterTurbo#99]
生成了56秒的视频，但是字幕只到29秒，后面就没有字幕了。

**Comment by harry0703** [comment]
可以把 任务文件夹下的 音频文件 mp3 和字幕文件 srt 上传上来，我定位一下么？
谢谢

**Comment by david-dong828** [comment]
我也是 字幕到15秒就没了
打包上传下 我的音频和srt 
[srt_audio.zip](https://github.com/harry0703/MoneyPrinterTurbo/files/14797693/srt_audio.zip)

**Comment by duffercn** [comment]
[audio_srt.zip](https://github.com/harry0703/MoneyPrinterTurbo/files/14797890/audio_srt.zip)

这是附件，谢谢！
> 可以把 任务文件夹下的 音频文件 mp3 和字幕文件 srt 上传上来，我定位一下么？ 谢谢

**Comment by harry0703** [comment]
@duffercn @david-dong828 
该问题已优化，可以更新代码后，再试试
有问题欢迎继续反馈👏🏻
